# Project 2

##### Imports

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
import kagglehub

c:\Users\fbase\All_vscode_projects\envs\ml-env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

##### 1. Run this section to load dataset

$$\huge \texttt{Data loading}$$

In [3]:
# Run this once for downloading the dataset
#url = "https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$limit=200000"
#df = pd.read_csv(url)

#df.to_csv("nyc_311_sample.csv", index=False)

In [4]:
df = pd.read_csv("nyc_311_sample.csv")
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.601042,-73.979387,POINT (-73.979387264647 40.601042365906)
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.743346,-73.886114,POINT (-73.886113509027 40.74334566695)
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
clean_status = pd.DataFrame([],columns=df.columns)
clean_status[df.columns] = np.full((1,44),False)

In [6]:
clean_status

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

##### 2. Take a peek at your dataset

$$\huge \texttt{Data overview}$$

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 44 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   unique_key                      200000 non-null  int64
 1   created_date                    200000 non-null  str
 2   closed_date                     158957 non-null  str
 3   agency                          200000 non-null  str
 4   agency_name                     200000 non-null  str
 5   complaint_type                  200000 non-null  str
 6   descriptor                      197180 non-null  str
 7   descriptor_2                    74933 non-null   str
 8   location_type                   162834 non-null  str
 9   incident_zip                    197358 non-null  float64
 10  incident_address                187723 non-null  str
 11  street_name                     187719 non-null  str
 12  cross_street_1                  136270 non-null  str
 13  cross_street_2                  136295 non-null  str
 14  intersection_street_1           127389 non-null  str
 15  intersection_street_2           127471 non-null  str
 16  address_type                    198295 non-null  str
 17  city                            189374 non-null  str
 18  landmark                        108403 non-null  str
 19  facility_type                   654 non-null     str
 20  status                          200000 non-null  str
 21  due_date                        746 non-null     str
 22  resolution_description          186218 non-null  str
 23  resolution_action_updated_date  187820 non-null  str
 24  community_board                 200000 non-null  str
 25  council_district                188316 non-null  float64
 26  police_precinct                 200000 non-null  str
 27  bbl                             166192 non-null  float64
 28  borough                         200000 non-null  str
 29  x_coordinate_state_plane        189407 non-null  float64
 30  y_coordinate_state_plane        189425 non-null  float64
 31  open_data_channel_type          200000 non-null  str
 32  park_facility_name              199888 non-null  str
 33  park_borough                    200000 non-null  str
 34  vehicle_type                    9530 non-null    str
 35  taxi_company_borough            152 non-null     str
 36  taxi_pick_up_location           2040 non-null    str
 37  bridge_highway_name             1643 non-null    str
 38  bridge_highway_direction        1215 non-null    str
 39  road_ramp                       1174 non-null    str
 40  bridge_highway_segment          1640 non-null    str
 41  latitude                        189398 non-null  float64
 42  longitude                       189398 non-null  float64
 43  location                        189398 non-null  str
dtypes: float64(7), int64(1), str(36)
memory usage: 67.1 MB

In [8]:
df.isna().sum()

unique_key                             0
created_date                           0
closed_date                        41043
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          2820
descriptor_2                      125067
location_type                      37166
incident_zip                        2642
incident_address                   12277
street_name                        12281
cross_street_1                     63730
cross_street_2                     63705
intersection_street_1              72611
intersection_street_2              72529
address_type                        1705
city                               10626
landmark                           91597
facility_type                     199346
status                                 0
due_date                          199254
resolution_description             13782
resolution_action_updated_date     12180
community_board                        0
council_district                   11684
police_precinct                        0
bbl                                33808
borough                                0
x_coordinate_state_plane           10593
y_coordinate_state_plane           10575
open_data_channel_type                 0
park_facility_name                   112
park_borough                           0
vehicle_type                      190470
taxi_company_borough              199848
taxi_pick_up_location             197960
bridge_highway_name               198357
bridge_highway_direction          198785
road_ramp                         198826
bridge_highway_segment            198360
latitude                           10602
longitude                          10602
location                           10602
dtype: int64

In [9]:
"""
for i in range(1,5):
    try:
        display(df.iloc[:,i:i*10].head())
    except:
        display(df.iloc[:,i*10:].head())
"""
#Looking at few columns makes it easier
subset1 = df.iloc[:,:11].head()
subset1

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET

In [10]:
subset2 = df.iloc[:,11:21].head()
subset2

,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status
0,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open
1,CONVENT AVENUE,WEST 133 STREET,WEST 135 STREET,NaN,NaN,BLOCKFACE,MANHATTAN,NaN,NaN,Open
2,NaN,NaN,NaN,AVENUE S,WEST 7 STREET,INTERSECTION,BROOKLYN,NaN,NaN,Open
3,79 STREET,WOODSIDE AVENUE,45 AVENUE,NaN,NaN,ADDRESS,ELMHURST,NaN,NaN,Closed
4,43 STREET,35 AVENUE,NORTHERN BOULEVARD,NaN,NaN,BLOCKFACE,QUEENS,NaN,NaN,Open

In [11]:
subset3 = df.iloc[:,21:31].head()
subset3

,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane
0,NaN,The Department of Transportation referred this...,2026-03-31T02:39:38.000,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN
1,NaN,The Department of Transportation referred this...,2026-03-31T02:30:56.000,09 MANHATTAN,NaN,Precinct 26,NaN,MANHATTAN,NaN,NaN
2,NaN,The Department of Transportation referred this...,2026-03-31T02:26:57.000,11 BROOKLYN,43.0,Precinct 62,NaN,BROOKLYN,989974.0,158253.0
3,NaN,DSNY already has a request to investigate this...,2026-03-31T12:00:00.000,04 QUEENS,25.0,Precinct 110,4.015250e+09,QUEENS,1015808.0,210118.0
4,NaN,The Department of Transportation referred this...,2026-03-31T02:17:11.000,01 QUEENS,NaN,Precinct 114,NaN,QUEENS,NaN,NaN

In [12]:
subset4 = df.iloc[:,31:].head()
subset4

,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UNKNOWN,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.601042,-73.979387,POINT (-73.979387264647 40.601042365906)
3,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.743346,-73.886114,POINT (-73.886113509027 40.74334566695)
4,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### 3. Cleaning

$$\huge \texttt{Data Cleaning}$$

###### Things I could do next time
1. Evaluate where we can remove NaN from
2. Seperate time from datetime columns
3. Evaluate the values of all columns do they all make sense or is there corrupted data

In [13]:
subset1.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET

Columns : Reason why null values appear
Closed dates : Because those service records have not been resolved?
>Does a service request being closed always mean that it has been resolved ( yes , no cause of something else , no without any reason )

In [14]:
"""
Q1 = [['question','answer']]
print("Try to answer in one line if possible")
for i in df.columns:
    question = f"How could {i} be the reason for closing a Service request?"
    print(question)
    answer = input(" Answer :")
    Q1.append([question,answer])

td = pd.DataFrame(Q1)
td.to_csv("Inventory.csv",columns=['question','answer'])
"""

'\nQ1 = [[\'question\',\'answer\']]\nprint("Try to answer in one line if possible")\nfor i in df.columns:\n    question = f"How could {i} be the reason for closing a Service request?"\n    print(question)\n    answer = input(" Answer :")\n    Q1.append([question,answer])\n\ntd = pd.DataFrame(Q1)\ntd.to_csv("Inventory.csv",columns=[\'question\',\'answer\'])\n'

1. A specific location/region could be the reason for closing or request
2. A specific type of problem could be the description for closing a request
3. A specific entity could be the reason for closing a request ( The work well so close more SR )

In [15]:
df['status'].unique()

<StringArray>
[       'Open',      'Closed', 'In Progress',    'Assigned',     'Started',
     'Pending', 'Unspecified']
Length: 7, dtype: str

In [16]:
cond1 = [df['closed_date'].notna(),df['closed_date'].isna()]
cd = ['not_null',np.nan]
ts = []
for i in range(2):
    for j in df['status'].unique():
        td = df[cond1[i]]
        try:
            td[td['status']==j].iloc[0]
            ts.append([cd[i],j])
        except:
            pass
            ts.append([cd[i],np.nan])

closed_date_x_status = pd.DataFrame(ts,columns=['closed_date','status'])
closed_date_x_status

   closed_date       status
0     not_null         Open
1     not_null       Closed
2     not_null          NaN
3     not_null     Assigned
4     not_null      Started
5     not_null      Pending
6     not_null  Unspecified
7          NaN         Open
8          NaN          NaN
9          NaN  In Progress
10         NaN     Assigned
11         NaN      Started
12         NaN      Pending
13         NaN  Unspecified

In [17]:
notnull_closed_dates = df[df['closed_date'].notna()]['closed_date']
pattern = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d+\.\d+$"
notnull_closed_dates.str.match(pattern).unique()

array([ True])

In [18]:
notnull_closed_dates.shape[0] + df[df['closed_date'].isna()].shape[0]
# This proves that except for the NaN ,  closed date has all valid string which follow this pattern (no rubbish value like unknown etc )

200000

In [19]:
notnull_closed_dates[notnull_closed_dates.duplicated(keep=False)]

75        2026-03-31T02:01:26.000
109       2026-03-31T01:54:57.000
159       2026-03-31T01:00:21.000
201       2026-03-31T01:54:57.000
203       2026-03-31T01:29:50.000
                   ...
199965    2026-03-30T19:37:43.000
199973    2026-03-14T15:54:00.000
199983    2026-03-13T00:00:00.000
199985    2026-03-12T12:59:01.000
199999    2026-03-13T08:56:36.000
Name: closed_date, Length: 51306, dtype: str

In [20]:
value = '2026-03-31T02:01:26.000'
notnull_closed_dates[notnull_closed_dates.str.match(value)]
# Okay there are some duplicated values , is this possible?

75      2026-03-31T02:01:26.000
1796    2026-03-31T02:01:26.000
Name: closed_date, dtype: str

In [21]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None):
    display(df.iloc[[75,1796],:])
# Okay two entries can be closed at the same time , sounds rare but its possible

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
75,68504007,2026-03-31T01:23:55.000,2026-03-31T02:01:26.000,NYPD,New York City Police Department,Noise - Commercial,Loud Talking,NaN,Club/Bar/Restaurant,11216.0,299 HALSEY STREET,HALSEY STREET,TOMPKINS AVENUE,THROOP AVENUE,TOMPKINS AVENUE,THROOP AVENUE,ADDRESS,BROOKLYN,HALSEY STREET,NaN,Closed,NaN,The New York City Police Department responded ...,2026-03-31T02:01:12.000,03 BROOKLYN,36.0,Precinct 79,3.018400e+09,BROOKLYN,1000520.0,188042.0,ONLINE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.682794,-73.941338,POINT (-73.94133816146 40.682793665961)
1796,68511460,2026-03-30T21:09:03.000,2026-03-31T02:01:26.000,NYPD,New York City Police Department,Illegal Parking,Blocked Crosswalk,NaN,Street/Sidewalk,11219.0,42 STREET,42 STREET,42 STREET,10 AVENUE,42 STREET,10 AVENUE,INTERSECTION,NaN,NaN,NaN,Closed,NaN,The New York City Police Department responded ...,2026-03-31T02:01:21.000,12 BROOKLYN,38.0,Precinct 66,NaN,BROOKLYN,985737.0,173516.0,ONLINE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.642938,-73.994642,POINT (-73.994641792031 40.642937837713)

In [22]:
print(df.duplicated().unique())
print(df.unique_key.duplicated().unique())
# No duplicate rows / entries

[False]
[False]

`closed_date` is completely clean

In [23]:
# Now are all these combinations of closed_data and status possible?
closed_date_x_status['Possible?'] = [0,1,1,0,0,0,1,1,0,1,1,1,1,0]
closed_date_x_status['Possible?'] = closed_date_x_status['Possible?'].astype('bool')
closed_date_x_status['description'] = ["Human error","Possible","Human error","Human error","Human error",
                                       "Human error","Human error","Possible","Human error","Possible",
                                       "Possible","Possible","Possible","Human error"]
closed_date_x_status
# This will be useful when we are using status column as our feature

   closed_date       status  Possible?  description
0     not_null         Open      False  Human error
1     not_null       Closed       True     Possible
2     not_null          NaN       True  Human error
3     not_null     Assigned      False  Human error
4     not_null      Started      False  Human error
5     not_null      Pending      False  Human error
6     not_null  Unspecified       True  Human error
7          NaN         Open       True     Possible
8          NaN          NaN      False  Human error
9          NaN  In Progress       True     Possible
10         NaN     Assigned       True     Possible
11         NaN      Started       True     Possible
12         NaN      Pending       True     Possible
13         NaN  Unspecified      False  Human error

In [24]:
#  1 means clean
#  2 means not clean
#  3 means that its not clean but I know which ones are not clean
# -1 means we assume its clean , because we are not gonna use it 
#  Boolean values mean , I haven't gone through them
clean_status[['unique_key','closed_date','status']] = [1,1,3]

In [25]:
print(df[df['created_date'].isna()].size)
# There are no null values in created_date

pattern = r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d+\.\d+$"


print(df['created_date'].str.match(pattern).unique()) # gives a boolean array where the pattern matches, False implies there are values which don't match this pattern , True implies there are values which match this pattern

print("No of duplicated values :",df['created_date'][df['created_date'].duplicated(keep=False)].size)
print("Total values : ",df['created_date'].shape[0])

0
[ True]
No of duplicated values : 55830
Total values :  200000

In [26]:
clean_status['created_date'] = 1

In [27]:
b = {k:df.iloc[:,k].unique() for k in [3,4,5]}
for k,v in b.items():
    print(k)
    print(v,'\n')

3
<StringArray>
[  'DOT',  'DSNY',  'NYPD',   'DHS',  'DCWP',   'OOS',   'OTI', 'DOHMH',
   'TLC',   'DPR',   'HPD',   'DEP',   'EDC',   'DOB',   'DOE']
Length: 15, dtype: str

4
<StringArray>
[                      'Department of Transportation',
                           'Department of Sanitation',
                    'New York City Police Department',
                    'Department of Homeless Services',
       'Department of Consumer and Worker Protection',
                              'Office of the Sheriff',
                'Office of Technology and Innovation',
            'Department of Health and Mental Hygiene',
                      'Taxi and Limousine Commission',
                 'Department of Parks and Recreation',
 'Department of Housing Preservation and Development',
             'Department of Environmental Protection',
                   'Economic Development Corporation',
                            'Department of Buildings',
                            'Department of Education']
Length: 15, dtype: str

5
<StringArray>
[          'Street Condition',          'Derelict Vehicles',
            'Illegal Parking',    'Noise - Street/Sidewalk',
                    'Traffic',        'Noise - Residential',
              'Drug Activity',            'Noise - Vehicle',
           'Blocked Driveway',            'Dirty Condition',
 ...
            'Trapping Pigeon',     'Highway Sign - Damaged',
         'School Maintenance',             'Found Property',
 'Municipal Parking Facility',                'Snow or Ice',
                 'Poison Ivy',    'Highway Sign - Dangling',
      'DEP Highway Condition',        'Cranes and Derricks']
Length: 166, dtype: str

In [28]:
for i in b[5]:
    print(i)

Street Condition
Derelict Vehicles
Illegal Parking
Noise - Street/Sidewalk
Traffic
Noise - Residential
Drug Activity
Noise - Vehicle
Blocked Driveway
Dirty Condition
Homeless Person Assistance
Consumer Complaint
Non-Emergency Police Matter
Noise - Park
Noise - Commercial
Cannabis Retailer
Urinating in Public
LinkNYC
Smoking or Vaping
Lost Property
Indoor Air Quality
Graffiti
Litter Basket Request
Curb Condition
Missed Collection
Encampment
Illegal Dumping
Abandoned Vehicle
Animal-Abuse
Drinking
Rodent
Street Light Condition
Street Sign - Damaged
Food Establishment
Vendor Enforcement
Illegal Tree Damage
Abandoned Bike
Damaged Tree
Panhandling
Illegal Posting
Obstruction
GENERAL
For Hire Vehicle Complaint
Noise
UNSANITARY CONDITION
PLUMBING
SAFETY
HEAT/HOT WATER
Outdoor Dining
Traffic Signal Condition
Dead Animal
Sewer
ELECTRIC
Water System
Noise - Helicopter
Food Poisoning
WATER LEAK
Lead
Illegal Fireworks
FLOORING/STAIRS
Hazardous Materials
Overgrown Tree/Branches
Sidewalk Condition
DOOR/WINDOW
Taxi Complaint
Air Quality
PAINT/PLASTER
Asbestos
Dumpster Complaint
Highway Condition
Residential Disposal Complaint
Root/Sewer/Sidewalk Condition
Maintenance or Facility
OUTSIDE BUILDING
Animal in a Park
ELEVATOR
Sanitation Worker or Vehicle Complaint
Bike/Roller/Skate
Water Conservation
Elevator
Indoor Sewage
New Tree Request
General Construction/Plumbing
Street Sweeping Complaint
Building/Use
Street Sign - Dangling
APPLIANCE
Taxi Report
Bus Stop Shelter Complaint
Plumbing
Electrical
Commercial Disposal Complaint
Special Projects Inspection Team (SPIT)
Uprooted Stump
Street Sign - Missing
Ferry Inquiry
Dead/Dying Tree
Mobile Food Vendor
Day Care
Unsanitary Pigeon Condition
Disorderly Youth
Unsanitary Animal Pvt Property
Broken Parking Meter
Emergency Response Team (ERT)
Boilers
Wood Pile Remaining
Real Time Enforcement
Lot Condition
Litter Basket Complaint
Violation of Park Rules
Bike Rack
Unleashed Dog
Bench
Drinking Water
Noise - House of Worship
Green Taxi Complaint
Construction Lead Dust
BEST/Site Safety
Bridge Condition
Public Toilet
Investigations and Discipline (IAD)
Industrial Waste
Scaffold Safety
Mold
Special Natural Area District (SNAD)
Harboring Bees/Wasps
Water Quality
Recycling Basket Complaint
Institution Disposal Complaint
For Hire Vehicle Report
E-Scooter
Beach/Pool/Sauna Complaint
Safety
Building Drinking Water Tank
Illegal Animal Kept as Pet
Illegal Animal Sold
Unsanitary Animal Facility
Non-Residential Heat
Lifeguard
Pet Sale
Ferry Complaint
Squeegee
Oil or Gas Spill
Tobacco or Non-Tobacco Sale
AHV Inspection Unit
Posting Advertisement
Tattooing
Animal Facility - No Permit
Highway Sign - Missing
Taxi Compliment
Bus Stop Shelter Placement
FHV Licensee Complaint
Cooling Tower
Incorrect Data
Plant
Dept of Investigations
Trapping Pigeon
Highway Sign - Damaged
School Maintenance
Found Property
Municipal Parking Facility
Snow or Ice
Poison Ivy
Highway Sign - Dangling
DEP Highway Condition
Cranes and Derricks

In [29]:
# agency , agency_name , complaint_type all have no null values
# After looking at their unique values , I can safely say that there are no corrupted values
clean_status[['agency','agency_name','complaint_type']] = [1,1,1]

In [30]:
for i in df['descriptor'].unique():
    print(i)
# All values look normal , it would be better to give this task to a LLM to validate if each value is valid
# furthermore descriptor and descriptor_2 don't have need to have value , therefore nan doesn't imply suspicious value

Pothole
Derelict Vehicles
Blocked Hydrant
Blocked Crosswalk
Loud Talking
Drag Racing
Loud Music/Party
Use Outside
Engine Idling
Banging/Pounding
No Access
Trash
Non-Chronic
Tobacco Sales
Trespassing
Suspicious Activity
Loud Television
Posted Parking Sign Violation
nan
Damaged/Defective
Allowed in Smoke Free Area
Car/Truck Music
Bag/Wallet
Ventilation
Graffiti
Car/Truck Horn
Replacement Basket
Double Parked Blocking Traffic
Human Feces
Blocked Bike Lane
Cave-in
Parking Permit Improper Use
Commercial Overnight Parking
Defacement
Use Indoor
Partial Access
Bulky Trash
Blocked Sidewalk
Removal Request
With License Plate
Other (complaint details)
Double Parked Blocking Vehicle
In Public
Rat Sighting
Fixture/Luminaire Out Of Position
Bus Stop
Street Light Out
Rodents/Insects/Garbage
Food Vendor
Roots Damaged
Chained to Public Property
Branch Cracked and Will Fall
Unauthorized Bus Layover
Broken Curb
Poster or Sign
Non-Food Vendor
Hotel or Motel
Neglected
Sidewalk Display
SIGNAGE MISSING
After Hours - Licensed Est
Driver Complaint - Non Passenger
Noise: Construction Equipment (NC1)
GARBAGE/RECYCLING STORAGE
WATER SUPPLY
FIRE ESCAPE
ENTIRE BUILDING
Merchandise
Noise: Construction Before/After Hours (NM1)
Restaurant Status
Noise: Alarms (NR3)
APARTMENT ONLY
Unlicensed
Controller
Cat
Sewer Backup (Use Comments) (SA)
OUTLET/SWITCH
SEWAGE
Noise: Boat(Engine,Music,Etc) (NR10)
Failed Street Repair
BATHTUB/SHOWER
PESTS
Hydrant Running (WC3)
Chemical Vapors/Gases/Odors
NYPD
Noise: Manufacturing Noise (NK1)
Book/Stationery
Defective Hardware
Noise: air condition/ventilation equipment (NV1)
1 or 2
MOLD
Leak (Use Comments) (WA2)
Lamppost Knocked Down
RADIATOR
Food Worker Activity
New Basket
Trash or Recycling
Catch Basin Search (SC2)
Branch or Limb Has Fallen Down
Plate Condition - Noisy
Food Contaminated
Other (Explain Below)
SLOW LEAK
Street Light Lamp Dim
Lead Kit Request (Residential) (L10)
Other
FLOOR
Noise, Barking Dog (NR5)
TOILET
Condition Attracting Rodents
Post
Oil Spill On Street, Small (HQS)
Car Wash
Overnight Commercial Storage
Hitting Building
Stoop Line Stand
License Plate Obscured
Newspaper Box Complaint
Trunk Damaged
Compost
DOOR
Dog Waste
Driver Complaint - Passenger
Line/Marking - After Repaving
Air: Odor/Fumes, Vehicle Idling (AD3)
Sales to Minors Under 21
WALL
CEILING
Paper License Plates
Sidewalk Violation
Dry Cleaner
Asbestos Complaint (B1)
Overflowing dumpster
Noise: Jack Hammering (NC2)
WINDOW GUARD BROKEN/MISSING
POWER OUTAGE
Manhole Overflow (Use Comments) (SA1)
Small uncovered dumpster
Pothole - Highway
Letter Grading
Cone
Possible Water Main Break (Use Comments) (WA1)
Rough, Pitted or Cracked Roads
Waste Set Out Too Early or Too Late
Chronic
CABINET
Chronic Dumping
NO LIGHTING
BASIN/SINK
DAMP SPOT
Trees and Sidewalks Program
Air: Odor/Fumes, Restaurant (AD2)
Hydrant Leaking (WC1)
Rodent Sighting
Broken Sidewalk
APS
Cell Phone Store
Site Setup Condition
Ped Flasher
BELL/BUZZER/INTERCOM
Flyer or Handbill
VENTILATION SYSTEM
SKYLIGHT
STEAM PIPE/RISER
STAIRS
WIRING
Dirty Water (WE)
WINDOW FRAME
WINDOW PANE
Noise: Private Carting Noise (NQ1)
Vehicle Signal
Veh Signal Lamp
Blocked - Construction
Recycling - Paper/Metal/Glass/Rigid Plastic
Barber Shop, Beauty Salon, or Nail Salon
CARBON MONOXIDE DETECTOR
SMOKE DETECTOR
Dog Off Leash
Garbage or Litter
Chemical Odor (HD1)
Graffiti or Vandalism
WINDOW/FRAME
Garage or Parking Lot
HEAVY FLOW
Tortured
MAINTENANCE
Street Light Cycling
Spilled Garbage
LIGHTING
Sign Inadequate
Litter
Structure - Outdoors
Signs of Rodents
Domestic Strays
Food Spoiled
Noise, Ice Cream Truck (NR4)
Illegal Use Of A Hydrant (CIN)
Elevator - Single Device On Property/No Alternate Service
Hydrant Knocked Over/Missing (WC)
Detached Trailer
Sidewalk Collapsed
Conduit
Line/Marking - Faded
Sewage Leak
DOOR FRAME
For One Address
Sewage Odor
Building Permit - None
Street Not Swept
Waste Left in Front of Other Residence
Zoning - Non-Conforming/Illegal Vehicle Storage
Speed Limit
Dirt or Gravel
ELECTRIC/GAS RANGE
Driver Report - Passenger
Cable
Used Car Dealer
Chronic Speeding
Dirty/Graffiti
Plumbing Work - Illegal/No Permit/Standpipe/Sprinkler
Electrical Wiring Defective/Exposed
Waste Disposal
Sewer Odor (SA2)
Illegal Conversion Of Residential Building/Space
Electronics/Phones
Bodega, Deli, or Convenience Store
Catch Basin Clogged/Flooding (Use Comments) (SC)
Catch Basin Grating Missing (SA4)
No Certificate Of Occupancy/Illegal/Contrary To CO
Pedestrian Ramp Defective
Other/Unknown
Bin Not Used
Storage Area Not Provided
Bulky Recycling
SRO - Illegal Work/No Permit/Change In Occupancy/Use
Sidewalk Zone Blocked
Privately Owned Public Space/Non-Compliance
Sign/Awning/Marquee - Illegal/No Permit
Remove Stump
Mattress or Box Spring Uncovered
St Name - Attached to Pole
Tree Alive - in Poor Condition
Trash or Recycling Not Secure
Lost and Found
Hitting Phone/Cable Lines
Dishwashing/Utensils
Building - Vacant, Open And Unguarded
Failure To Retain Water/Improper Drainage- (LL103/89)
Elevator - Multiple Devices On Property
Planted More Than 2 Years Ago
Unsafe Driving
Injured Wildlife
Food Temperature
Donation Collection Bin
Day Care Facility
Plate Condition - Shifted
Pigeon Waste
Water Meter Broken/Leaking - Private Residence (CMR)
REFRIGERATOR
Playing in Unsuitable Place
Rat or Mouse
Dog
Fence - None/Inadequate
Blocking Street
Out of Order
Unsecured Facility
Recycling - Paper
Permit/License/Certificate
After Hours Work - Illegal
COOKING GAS
Boiler - Defective/Inoperative/No Permit
Police Report Requested
Waste Not Separated
Remove Debris
Home Improvement Contractor
Air: Dust, Construction/Demolition (AE4)
LOW WATER PRESSURE - WLWP
Curb Defect-Metal Protruding
Street Fair Vendor
Pedestrian Signal
No Parking, Standing, Stopping
Site Conditions Endangering Workers
MAILBOX
Working Contrary To Stop Work Order
Other Store (Non-Food)
Rooftank Leak Or Overflow (CKO)
Stop
Dust from Construction
Bird
Illegal Hotel Rooms In Residential Building
Work Without A Permit - Occupied Multiple Dwelling
Landlord or Real Estate Agent
Tree Leaning/Uprooted
Water Meter Broken/Leaking - Other (CMO)
Overflowing
Other Animal
Sidewalk Shed/Pipe Scafford - Inadequate Defective/None
Inadequate Sweeping
Street Light Feed
Entire Tree Has Fallen Down
Hitting Power Lines
Unsafe Use of Playground
Air: Other Air Problem (Use Comments) (AZZ)
Coin or Card Did Not Register
Blocking Sidewalk or Street
No Water (WNW)
Storage Warehouse
Biking/Rollerblading off Path
Street Cleaning - ASP
Dead Animal
Broken Glass
Clothing, Shoe, or Accessories Store
Building Shaking/Vibrating/Structural Stability
JANITOR/SUPER
Supermarket or Grocery Store
Bare Hands in Contact w/ Food
Abandoned Bike
RAIN GARDEN PLANTING (GIRGP)
Sticker or Decal
Sign
Unleashed Dog in Public
Mouse Sighting
Gift, Novelty, or Souvenir Store
Truck Route Violation
Recycling - Metal/Glass/Rigid Plastic
One Way
Egress - Doors Locked/Blocked/Improper/No Secondary Means
Chained
Veh Signal Head
Ped Multiple Lamps
Obstructing Public Use
Chronic Stoplight Violation
Gas Station Pumps
Damaged/Bent/Loose/Leaning
Grass/Weeds
RAIN GARDEN DEBRIS (GIRGD)
Tow Truck Company
Branches Damaged
Unsafe Mold Cleanup
Curb Cut/Driveway/Carport - Illegal
Hydrant Defective (WC2)
Manhole Cover Missing (Emergency) (SA3)
Dumpster - Construction Waste
Pet/Animal
DOOR/FRAME
Glassware Hanging
Raccoon
Clothing/Glasses
Street Flooding (SJ)
Weeds or Grass
Debris - Excessive
General Vendor
Construction Debris
Hours of Operation
No Receipt
Illness Caused by Drinking Water
Police Report Not Requested
Adjacent Buildings Not Protected
Wasting Faucets,Sinks,Flushometer,Urinal,Etc. - Other (CWO)
LED Pedestrian Unit
Unlicensed Vendors
Trash and Bulky Trash
Vent/Exhaust - Illegal/Improper
Water Meter Stolen/Missing - Private Residence (CLR)
No Permit or License
Dead Branches in Tree
DOOR TO DUMBWAITER
Plumbing
Coming into Apartment
Veh Signal Lens
Safety Netting/Guard Rails - Damaged/Inadequate/None (Over 6 Stories/75 Feet)
Illegal. Commercial Use In Resident Zone
Decorative Necklace Lighting
Failure to Comply with Vacate Order
Smoking
Debris - Falling Or In Danger Of Falling
Missing
Sidewalk Grating - Defective
Excessive Water In Basement (WEFB)
Cons - Contrary/Beyond Approved Plans/Permits
Lamppost Leaning
St Name - Over Intersection
Waste Left in Front of Residence
Booting Company
Hydrant Running Full (WA4)
Wireless
Unauthorized Tree Removal
Ped Lamp
Drug Store or Pharmacy
Lamppost Damaged
Food Source/Protection
Blocked - ATM
Failure To Maintain
Air: Smoke, Vehicular (AA4)
Culvert Blocked/Needs Cleaning (SE)
Unsafe Chemical, Abandoned (HC2)
Damaged Other
In Common Areas
Multiple Street Lights Out
Fixture/Luminaire Hanging
Plumbing Work - Unlicensed/Illegal/Improper Work In Progress
Toilet Facility
Gas Station Convenience Store
Metal Protruding - Sign Stump
Syringes
Removing Wildlife
Lamppost Base Door/Cover Damaged
Waterway-Color (IHD)
Car Service Company Complaint
Chemical Spill/Release (HA1)
Recreation Center
Laundromat
PAVEMENT
Common Areas and Apartment
Debris from Car Accident
Air: Dust, Other (Use Comments) (AE5)
Planted Less Than 2 Years Ago
Plumbing-Defective/Leaking/Not Maintained
Advertising Sign/Billboard/Posters/Flexible Fabric - Illegal
Gas Hook-Up/Piping - Illegal Or Defective
Suspended (Hanging) Scaffolds - No Pmt/Lic/Dangerous/Accident
Traffic Signal Light
Painted Line/Marking
Public Complaint - Comm Location
Yield
Street Light Lamp Missing
Inappropriate Behavior
Electronics or Appliance Repair
Odor In Sewer/Catch Basin (ICB)
Congestion/Gridlock
Lamppost Wire Exposed
New Con Ed Service Request
Graffiti - Highway
Illegal Tree Removal/Topo. Change in SNAD
Unauthorized Climbing
Lamppost Base Door/Cover Open
Catch Basin Sunken/Damaged/Raised (SC1)
Air: Smoke, Chimney or vent (AS1)
Opossum
Missing/Stump
Bees/Wasps - Not a beekeper
Taste/Odor, Musty/Stale (QA4)
Crash Cushion Defect
Demolition - Unsafe
Residential Rental Agency
Wholesale Food Market
Kitchen/Food Prep Area
Trash Not Separated from Recycling
3 or More
Equipment
Rough Pavement
Car Service Company Report
Bicycle Chained to Tree
Misuse
ROOFING
Wastewater Into Catch Basin (IEB)
SPRINKLER
Noise
Improperly Parked or Abandoned
Posted Notice Or Order Removed/Tampered With
Restaurant
Idling or Blocking Traffic
Toxic Chemical/Material
Support Bracket
Veh Signal Visor
Squirrel
Noise:  lawn care equipment (NCL)
Illegal Conversion Of Commercial Bldg/Space To Other Uses
Bike Signal
No Shelter
Food Worker Hygiene
Food Contains Foreign Object
Street Zone Blocked
Third-Party Food Delivery Service
Cellar Door Open/Unprotected
Wall/Retaining Wall - Bulging/Cracked
Underage - Licensed Est
Beach/Pool Water
Sports Equipment
Graffiti/Dirty Condition
Structure - Indoors
Food Protection
Ticket Seller
Air: Odor, Sweet From Unknown Source (AZ1)
Structural Stability Impacted - New Building Under Construction
Driver Report - Non Passenger
Base Door
E-Cigarette Sales
Safety
Defective/Missing Curb Piece (SC4)
Unsanitary Condition
Highway Fence
Facility Maintenance
Construction
Home Heating Oil Company
Tree Trunk Split
Taste/Odor, Chemical (QA2)
Waterway-Sewage (IHA)
Sign - In Danger Of Falling
Refrigerator or Freezer Door Attached
Lamppost Base Door/Cover Missing
Furniture Store
Cloudy Or Milky Water (QB1)
Detour
Hyd Valve Box Cover Missing (WV2)
Product Concerns
Rooster
Noise, Other Animals (NR6)
Animal Waste
Monkey
For-Profit College or University
Odor
Deer
Cellar Door Defective
Street Light Dayburning
Ver Mesage Sign RTPI
Too Close to a School
Inadequate or No Heat
Lights From Parking Lot Shining On Building
Scale Dealer or Repairer
Electronics Store
Depression Maintenance
Automated Employment Decision Tool Use
Grease In Sewer/Catch Basin (IDG)
Tax Preparation Services
Absent
Landmark Bldg - Illegal Work
Animals Sold From Residence
Domestic Worker Employment Agency
installation of hydrant side post (WHFP)
Wasting Faucets,Sinks,Flushometer,Urinal,Etc. - Private Residence (CWR)
Do Not Enter
Vehicle Complaint
Handwashing
Process Server
Cleanliness
Investigative Inspection
Timer Defect - Fast/Fail
Food Preparation Location
Emergency Personnel Report
Oil Spill On Street, Large (HQL)
Original Labels or Packaging Not Kept
Dealer in Products for the Disabled
Facility Construction
Car Rental
Veh Signal Sec Door
Shipping Company
After Hours Work - With An AHV Permit
Unauthorized Film Shoot
Lighting
Chemical Spill (IAC)
Canopy Complaint
Fixture/Luminaire Damaged
BBQ Outside Authorized Area
Equipment Complaint
Damaged Bench
Employment Agency
Dry Cleaning Vapors (PERC)
Moving Company
Construction - Change Grade/Watercourse
Lamppost Missing
Banned Tobacco Flavors Sold
Farm Animal
Multiple St Lts Dayburning
Building
Pigeon Odor
Safety Netting/Guard Rails - Damaged/Inadequate/None (6 Stories/75 Feet Or Less)
Unsafe Worksite
Affecting Sewer or Foundation
Ped Visor
Fixture/Luminaire Door Open
Dirt, Debris, Litter Complaint
Veh Sgnl Mult Lamps
Clear Street Light
Animal Odor
Smoke/Odor
Push Button
Newsstand
Barrier Condition
New Automatic Public Toilet Request
Tattoo Artist Unlicensed
Taste/Odor, Bitter/Metallic (QA3)
SEWER
Use of Newly Seeded Lawn
Debt Collection Agency
Sprinkler System - Inadequate
Warning Signal
General Complaint
Bent/Loose
Temporary
Junction Box
Clear Water With Other Particles (Use Comments) (QEZ)
No Sampling Required, Requested Information (QG2)
Online or Mail Order
Department Store or Megastore
Sidewalk Staircase
Controller Cabinet
Containers Left Out After Collection
Guard Rail - Street
Illegal Use Of Hose - Other (CCO)
Nuisance/Truant
Construction Labor Provider
Underground
Unauthorized Tree Pruning
News Gathering
Cat Sold
Pedestrian Sign
School Crossing
Snake
unknown odor/taste in drinking water (QA6)
Mast Arm
On Messenger
Bracket Arm Loose
Graffiti - Bridge
Vehicle Report
Air: Odor, Nail Salon (AD8)
Plate Condition - Open
Smoking, Cigar, or Vape Store
Driver Compliment
New Bus Stop Shelter Placement
No Permit
Licensee Complaint
Parking Card Stuck in Meter
Turn Signal
Dog Sold
Jewelry Store
Credit Card Stuck in Meter
Time Switch
Inadequate Support Shoring
Door Lock
Material Storage - Unsafe
Wood Pole Equipment
Highway Flooding (SH)
Removing Flowers/Plants
Parking Corral Not Maintained
Too Close to a House of Worship
Smoking Ban - Smoking on Construction Site
Office Supply or Stationery Store
Door to Door Sales
Foreign Attachment On Lamppost
Bracket Arm Bent
Unsafe Chemical, Storage (HC1)
Concrete In Catch Basin (IEA)
Collection Days
Excavation Undermining Adjacent Building
PORCH/BALCONY
GUTTER/LEADER
DRY WEATHER DISCHARGE - DWD
Dirty/Inadequate Eqp/Facility
Traffic Sign or Signal Blocked
Flood Light Lamp Dim
Loose Plate
Adult Establishment
Jewelry
Plants- Odor Related Problems (PO1)
Wildlife Sighting
MICROWAVE
Damaged or Missing Ad Box
Hardware Store
Clear Water With Organisms (Insects, Worms) (QE2)
Glassware Missing
Water
Milk/Dairy Products
Touchscreen/Button Not Working
Beach/Pool/Sauna Unpermitted
Oil Spill Into Basin/Sewer - Small (IABS)
Ped Lens
Exit/Route
Integrity Complaint Referral
Food Worker Illness
Recycling Posters Not Posted
Insects / Pests
Wear & Tear
Smoking Signs - "No Smoking" Signs Not Observed on Construction Site
Warning Signal Lamp
Noise: Other Noise Sources (Use Comments) (NZZ)
ROOF DOOR/HATCH
Cloudy Or Milky, Other (Use Comments) (QBZ)
Taste/Odor, Chlorine (QA1)
Oil Spill Into Basin/Sewer - Large (IABL)
Home Appliance Store
Other School Condition
Plumbing Problem
Pedicab
Pawnbroker
Pet Store
Water Meter Stolen/Missing - Other (CLO)
Fixture/Luminaire Missing
RAIN GARDEN STRUCTURE (GIRGS)
In Car
General Maintenance
Rodents/Mice
Roadway
Travel Agency
BOILER
Disruptive Passenger
Snow or Ice
Flood Light Lamp Out
Sign Blocked by Tree
Speed Board Sign
Street Con Game
Funeral Home
Unclean Condition
Heating Problem
Controller Flasher
Plate Condition - Anti-Skid
Beekeeping - Honeybees
Time Clock Maladjusted
Locksmith
Plate Condition - DEP
Illegal Use Of Hose - Private Residence (CCR)
Unauthorized Posting of Signs
Sodium Warning
Concrete Barrier
Sign Missing or Defective
Tour Bus
Art Supply Store
Vehicle
Bracket Arm Broken
Snow Removal Requested
Restrooms
Allergy Information
Crane/Suspension Scaffold - No Permit/License/Cert./Unsafe/Illegal

In [31]:
clean_status[['descriptor','descriptor_2']]=[-1,-1]
# -1 means we assume its clean , because we are not gonna use it 
# we have to give it some value because bool value implies we haven't touched that column

In [32]:
for i in df['location_type'].unique():
    print(i)

# Clean

nan
Street
Street/Sidewalk
Residential Building/House
Sidewalk
Park/Playground
Club/Bar/Restaurant
Store/Commercial
Residential Building
Taxi
3+ Family Apartment Building
Comercial
3+ Family Apt. Building
Curb
Other
Yard
Subway Station
Restaurant/Bar/Deli/Bakery
Business
RESIDENTIAL BUILDING
Subway
Above Address
Gutter
1-2 Family Dwelling
Park
Speed Reducer
Highway
Street/Curbside
Other (Explain Below)
Residential
Crosswalk
Bus Stop Shelter
Retail Store
3+ Family Mixed Use Building
Ferry
Mixed Use
Mobile Food Vendor
Private House
Apartment
Vacant Lot
House of Worship
Lot
Public/Unfenced Area
Traffic Island or Median
Commercial Building
Private School
Hallway
Food Establishment or Vendor
Parking Lot or Garage
Catering Service
Bridge
Alley
Vacant Building
1-3 Family Dwelling
Lobby
1-2 Family Mixed Use Building
Office Building
Non-Profit
Vehicle Lane
Residence
Day Care or Nursery
Cafeteria - Public School
Intersection
Terminal
Beach
Public Garden
School
Inside
Permanent Food Stand
Store
Kennel/Animal Shelter
Building (Non-Residential)
Public School
House and Store
Pool
Private Residence
1-3 Family Mixed Use Building
Common Area
Overpass
Stairwell
Roadway Tunnel
Medical Facility
Senior Center
Commercial
Groomer
Street Vendor
Tattoo Parlor
Hospital
Green Cart Vendor
Bike Lane
Food Cart Vendor
Other (explain in Complaint Details)
Airport or Train/Bus Station
School Safety Zone
Ground
Cafeteria - College/University
Private Property
Government Building
Spa Pool
Building Entrance
Homeless Shelter
Pier
Restaurant
School - K-12 Public
Roof
Horse Stable
School - K-12 Private
Cafeteria - Private School
Steam Room
Sauna

In [33]:
for i in df['incident_zip'].unique():
    print(i)

nan
10031.0
11223.0
11373.0
11101.0
10002.0
11207.0
10453.0
11435.0
11224.0
10467.0
10455.0
11412.0
11222.0
11102.0
11234.0
11368.0
10040.0
10032.0
10014.0
11209.0
10468.0
10473.0
10039.0
11233.0
10012.0
11433.0
11206.0
11106.0
11385.0
10304.0
10019.0
10460.0
11355.0
10030.0
10466.0
10001.0
10451.0
11365.0
11220.0
11217.0
10463.0
11237.0
11432.0
10459.0
11232.0
10037.0
10027.0
11216.0
11369.0
10462.0
11354.0
11379.0
10452.0
10472.0
11360.0
10454.0
10457.0
11417.0
10301.0
10458.0
11225.0
11418.0
10029.0
10011.0
10456.0
11235.0
11414.0
11370.0
11219.0
10023.0
11218.0
11226.0
11356.0
10026.0
11427.0
11361.0
11229.0
10470.0
10306.0
11230.0
11221.0
10003.0
11691.0
11201.0
11377.0
10036.0
11239.0
11413.0
10009.0
10004.0
11204.0
10128.0
11211.0
10035.0
10013.0
11210.0
11231.0
11375.0
11213.0
11203.0
11214.0
11208.0
11378.0
11434.0
10022.0
10461.0
10000.0
11420.0
11372.0
11205.0
11429.0
11040.0
10018.0
11416.0
11428.0
11364.0
10075.0
11105.0
11104.0
10007.0
10034.0
11374.0
10033.0
11358.0
11415.0
10469.0
10016.0
11238.0
11212.0
10309.0
10314.0
10006.0
11436.0
11692.0
11419.0
11228.0
10475.0
11236.0
11422.0
10024.0
10021.0
11103.0
10025.0
11249.0
10017.0
11357.0
10465.0
10005.0
10471.0
11421.0
10474.0
10065.0
11215.0
10310.0
11423.0
11426.0
11694.0
11693.0
11697.0
11430.0
11411.0
10038.0
11367.0
11366.0
10312.0
10303.0
10302.0
10305.0
10121.0
10028.0
10010.0
10308.0
11362.0
11363.0
10044.0
10464.0
10282.0
10106.0
11109.0
10280.0
10151.0
10307.0
10281.0
11004.0
10174.0
10523.0
10069.0
11001.0
10172.0
12345.0
10020.0
10169.0
10153.0
10154.0
11251.0
10105.0
10170.0
10168.0
11721.0
10271.0
10165.0
10278.0
29602.0
10119.0
10171.0
10107.0
10179.0
10122.0
11242.0
10120.0
11241.0
11371.0
10045.0
11005.0
10176.0
10080.0
10110.0
10118.0
8854.0
11359.0
11695.0
10178.0
10112.0
10175.0
10166.0
10177.0
10048.0
11096.0
10103.0

In [34]:
a = (df[df['incident_zip'].notnull()]['incident_zip']).unique()
if (a > 501).all() and (a < 11697).all(): # Nyc zip codes are between 00501 – 11697
    print(True)
else:
    print(a[a>14952]) 

# This zip code belongs to  Greenville, South Carolina which is not in New
# No clue what its doing here in nyc SR dataset

[29602.]

In [35]:
with pd.option_context('display.max_rows',None,
                       'display.max_columns',None):
    display(df[df['incident_zip']>14952])

# Even the city of incident is Greenville , logically this shouldn't be in nyc SR dataset but its a valid entry

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
46272,68469749,2026-03-26T16:03:27.000,NaN,DCWP,Department of Consumer and Worker Protection,Consumer Complaint,Debt Collection Agency,Contract or Billing Dispute,Business,29602.0,NA PO BOX 1269,PO BOX 1269,NaN,NaN,NaN,NaN,NaN,GREENVILLE,NaN,NaN,In Progress,NaN,The Department of Consumer and Worker Protecti...,2026-03-27T09:56:52.000,0 Unspecified,NaN,Unspecified,NaN,Unspecified,NaN,NaN,ONLINE,Unspecified,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
for i in df['incident_address'].unique():
    print(i)

# All addresses look valid , I don't know if these are real addresses , we are gonna assume that they are

65 ROAD
CONVENT AVENUE
nan
42-71 79 STREET
43 STREET
ELDRIDGE STREET
74 ARLINGTON AVENUE
WEST BURNSIDE AVENUE
HARRISON AVENUE
139-22 87 DRIVE
90-36 149 STREET
3246 BAYVIEW AVENUE
JEROME AVENUE
1768 WALTON AVENUE
414 EAST 152 STREET
RYE PLACE
RISSE STREET
26 WEST STREET
454 AVENUE U
18-27 25 ROAD
1272 EAST 70 STREET
101-20 MARTENSE AVENUE
89 THAYER STREET
531 WEST 159 STREET
273 BENNETT AVENUE
2737 WEST 33 STREET
543 80 STREET
108 FIELD PLACE
2275 RANDALL AVENUE
2911 8 AVENUE
FULTON STREET
219 WEST 145 STREET
354 WADSWORTH AVENUE
2518 WEST 1 STREET
20 PRINCE STREET
108-26 159 STREET
251 BUSHWICK AVENUE
25-15 BROADWAY
801 SENECA AVENUE
1590 UNDERCLIFF AVENUE
180 PARK HILL AVENUE
81 MADISON STREET
705 9 AVENUE
121 MT HOPE PLACE
EAST TREMONT AVENUE
138-15 FRANKLIN AVENUE
121 MOUNT HOPE PLACE
WEST  137 STREET
4127 WICKHAM AVENUE
311 11 AVENUE
209 JAMAICA AVENUE
929 COURTLANDT AVENUE
188-35 69 AVENUE
68 STREET
310 LIVINGSTON STREET
2676 HEATH AVENUE
188-25 71 CRESCENT
GATES AVENUE
86 ROAD
896 HOME STREET
1159 EAST 178 STREET
4114 9 AVENUE
647 WEST 172 STREET
1790 STILLWELL AVENUE
2155 MADISON AVENUE
127 WEST 141 STREET
21 NOLL STREET
930 SHERIDAN AVENUE
35 ST NICHOLAS TERRACE
86 AVENUE
299 HALSEY STREET
5 ARMAND PLACE
160 ORCHARD STREET
LA GUARDIA AIRPORT
2754 CRESTON AVENUE
2079 BENEDICT AVENUE
137-72 NORTHERN BOULEVARD
670 PACIFIC STREET
74 STREET
80 WEST 170 STREET
1001 SOUNDVIEW AVENUE
676 LINCOLN PLACE
209-20 18 AVENUE
ALEXANDER AVENUE
382 GRANDCONCOURSE
2075 ANTHONY AVENUE
107-74 77 STREET
115 STUYVESANT PLACE
35-03 12 STREET
EAST 178 STREET
2320 VALENTINE AVENUE
1016 UNION STREET
85-55 115 STREET
335 EAST 111 STREET
137 BENZIGER AVENUE
2 WEST NINTH STREET
1420 GRAND CONCOURSE
206 WEST 148 STREET
35-19 12 STREET
923 SIMPSON STREET
227 EAST 178 STREET
198 STANTON STREET
230 BROOK AVENUE
130-03 HILLSIDE AVENUE
2541 EAST 12 STREET
156-41 80 STREET
2895 GRAND CONCOURSE
68-33 62 STREET
1615 ST JOHNS PLACE
3242 DECATUR AVENUE
635 MORRIS AVENUE
2026 RYER AVENUE
103-36 98 STREET
4315 12 AVENUE
314 PATCHEN AVENUE
3209 DECATUR AVENUE
127 WEST 70 STREET
1437 40 STREET
3 AVENUE
97-22 57 AVENUE
950 EAST 181 STREET
3833 WHITE PLAINS ROAD
95 LINDEN BOULEVARD
346 BERGEN STREET
13-05 133 PLACE
31 WEST 110 STREET
37-22 101 STREET
89-53 208 STREET
42-39 BELL BOULEVARD
1511 37 STREET
2341 EAST 24 STREET
372 EAST 235 STREET
547 WEST 157 STREET
280 MILL ROAD
112-25 167 STREET
1030 41 STREET
1947 OCEAN AVENUE
21 EAST 108 STREET
462 WEST 157 STREET
1087 BROADWAY
74 ST MARKS PLACE
578 EAST 141 STREET
254 WEST 57 STREET
12 CROWN STREET
2713 WALLACE AVENUE
CROMMELIN STREET
NAMEOKE AVENUE
469 WEST 157 STREET
120 LAWRENCE STREET
270 KNICKERBOCKER AVENUE
308 EAST 151 STREET
1340 STRATFORD AVENUE
79-17 CYPRESS AVENUE
133 RUSSELL STREET
2226A FIRST AVENUE
LAUREL HILL BOULEVARD
97-24 ALLENDALE STREET
340 BAINBRIDGE STREET
410 WEST 128 STREET
2311 SOUTHERN BOULEVARD
65 EAST 183 STREET
800 GREENWOOD AVENUE
255 WEST 43 STREET
419 SCHROEDERS AVENUE
130 AVENUE
734 EAST    9 STREET
54 STONE STREET
203 HULL STREET
1465 WASHINGTON AVENUE
18 AVENUE
34-46 VERNON BOULEVARD
650 SCHROEDERS AVENUE
1806 1 AVENUE
89-08 SUTTER AVENUE
1004 UNION STREET
342 BAINBRIDGE STREET
17 VAN SICLEN AVENUE
556 SCHROEDERS AVENUE
95 NEPTUNE AVENUE
2362 EAST 21 STREET
526 SCHROEDERS AVENUE
358 43 STREET
394 MONTGOMERY STREET
97 AVENUE
323 GRAHAM AVENUE
505 EAST 120 STREET
78 STREET
516 SCHROEDERS AVENUE
3571 NOSTRAND AVENUE
60 LAFAYETTE STREET
2830 BRIGHTON 3 STREET
1166 ELTON STREET
950 EAST 4 WALK
141 NAGLE AVENUE
LIVINGSTON STREET
3114 AVENUE I
472 HENRY STREET
1152 ELTON STREET
101-09 34 AVENUE
72-07 AUSTIN STREET
109 EAST 130 STREET
87 UTICA AVENUE
726 WALKER STREET
55 STAGG STREET
170 CROSBY STREET
833 EAST 52 STREET
1113 ASHFORD STREET
1461 SHORE PARKWAY
169 MCKINLEY AVENUE
878 HART STREET
494 VANDALIA AVENUE
15 ADRIAN AVENUE
133 EAST 110 STREET
1151 COLGATE AVENUE
64-14 PERRY AVENUE
48 STAGG STREET
475 VANDALIA AVENUE
284 HUMBOLDT STREET
118-40 180 STREET
1773 74 STREET
983 EAST 43 STREET
2045 STORY AVENUE
475 LOCKE STREET
160 EAST 52 STREET
1062 RHINELANDER AVENUE
2925 BRIGHTON 8 STREET
2039 BLACKROCK AVENUE
2660 HARING STREET
1750 DEAN STREET
118-44 180 STREET
535 HAVEMEYER AVENUE
889 EAST 37 STREET
511 WEST 147 STREET
4506 GLENDALE COURT
131 AVENUE C
86 STANTON STREET
6912 16 AVENUE
162 EAST 2 STREET
1373 TELLER AVENUE
CENTRAL PARK
747 EAST 217 STREET
40 GATLING PLACE
130-40 129 STREET
1399 JEFFERSON AVENUE
1940 LEXINGTON AVENUE
35-33 93 STREET
GRAND STREET
102 MACON STREET
50-03 30 AVENUE
1259 GRANT AVENUE
1921 BAY AVENUE
1326 MORRISON AVENUE
1379 JEFFERSON AVENUE
WILLOUGHBY AVENUE
26 3 AVENUE
400 SHEPHERD AVENUE
1339 MORRISON AVENUE
996 HERKIMER STREET
1569 HOE AVENUE
22-58 79 STREET
3343 SEDGWICK AVENUE
1632 EAST 174 STREET
115 EAST MOSHOLU PARKWAY NORTH
1729 67 STREET
51-27 65 PLACE
1624 EAST 172 STREET
144 EAST 7 STREET
234 EAST 198 STREET
1420 AMSTERDAM AVENUE
6703 11 AVENUE
93 PITT STREET
1902 7 AVENUE
1 WEST 127 STREET
208-14 109 AVENUE
538 HART STREET
824 EAST 9 STREET
3231 CRUGER AVENUE
310 NEW LOTS AVENUE
1577 HOE AVENUE
67-15 DARTMOUTH STREET
GERARD AVENUE
1409 NEW YORK AVENUE
630 ST ANNS AVENUE
86-29 155 AVENUE
44-30 MACNISH STREET
324 BAY RIDGE AVENUE
439 CASTLE HILL AVENUE
850 3 AVENUE
272-01 UNION TURNPIKE
309 86 STREET
510 ATLANTIC AVENUE
320 WEST 38 STREET
166 1 AVENUE
1847 UNIVERSITY AVENUE
18-42 25 ROAD
133-34 41 AVENUE
17 WEST 125 STREET
103-01 101 AVENUE
209-23 JAMAICA AVENUE
97-28 81 STREET
1614 HAIGHT AVENUE
266 IRVING AVENUE
313 59 STREET
405 EAST 92 STREET
221-00 HORACE HARDING EXPRESSWAY
44-25 MACNISH STREET
366 CLIFTON PLACE
44-21 MACNISH STREET
4615 3 AVENUE
50 EAST 80 STREET
SUYDAM STREET
2856 BRONX PARK EAST
29 STREET
261 DRIGGS AVENUE
525 EAST 21 STREET
VAN DAM STREET
1026 ST NICHOLAS AVENUE
20 AVENUE
2686 BAILEY AVENUE
2016 REGENT PLACE
61-17 MASPETH AVENUE
245 CANAL STREET
104-07 LIBERTY AVENUE
45-36 39 PLACE
221 EAST 138 STREET
PROSPECT PLACE
810 EAST 170 STREET
82 READE STREET
3784 10 AVENUE
1792 WEST 10 STREET
1981 AMSTERDAM AVENUE
1794 WEST 10 STREET
2375 OCEAN AVENUE
2857 VALENTINE AVENUE
195-60 PECK AVENUE
225 EAST 163 STREET
107-40 160 STREET
141 WASHINGTON AVENUE
25-12 149 STREET
55 PARADE PLACE
CLOVE ROAD
1173 GRAND CONCOURSE
454 FORT WASHINGTON AVENUE
107 STREET
706 BROOK AVENUE
264 MILL ROAD
842 FRANKLIN AVENUE
1391 DEAN STREET
651 EAST 183 STREET
45-76 162 STREET
1574 SAINT MARKS AVENUE
745 GATES AVENUE
WEST 25 STREET
1869 83 STREET
574 WEST 235 STREET
979 GRANT AVENUE
118 EAST 35 STREET
156-19 86 STREET
58 STONE STREET
65-50 WETHEROLE STREET
624 PARK AVENUE
83-16 LEFFERTS BOULEVARD
2385 WILLIAMSBRIDGE ROAD
250 EAST   30 STREET
623 ELTON STREET
1680 BEDFORD AVENUE
325 CANAL STREET
831 7 AVENUE
2016 DAVIDSON AVENUE
621 RUTLAND ROAD
2 ADRIAN AVENUE
400 WEST 25 STREET
980 ATLANTIC AVENUE
1900 GRAND CONCOURSE
270 MOTHER GASTON BOULEVARD
11 BARRY STREET
256 EAST 166 STREET
1769 VYSE AVENUE
422 BLAKE AVENUE
1621 ST NICHOLAS AVENUE
BLEECKER STREET
386 EAST 161 STREET
309 PATCHEN AVENUE
156-24 86 STREET
266 WASHINGTON AVENUE
EAST 4 STREET
1247 BEACH AVENUE
11 TRINITY PLACE
1155 EAST   35 STREET
1645 ST NICHOLAS AVENUE
75-19 66 DRIVE
12 VESTRY STREET
HURON STREET
2939 WILKINSON AVENUE
176 CLARKSON AVENUE
107-48 160 STREET
94-40 77 STREET
86-11 WHITNEY AVENUE
114-12 144 STREET
330 WEST 30 STREET
75-00 AMSTEL BOULEVARD
88 GREENWICH STREET
950 UNDERHILL AVENUE
40 BRUCKNER BOULEVARD
65 ST TRANSVERSE
3016 BRIGHTON 6 STREET
110 CADMAN PLAZA EAST
1399 DEAN STREET
2 AVENUE
EAST  161 STREET
1254 UNION STREET
836 FRANKLIN AVENUE
3540 ROCHAMBEAU AVENUE
PITKIN AVENUE
1925 7 AVENUE
3810 BAILEY AVENUE
561 MYRTLE AVENUE
134 BOWERY
105-06 132 STREET
2852 GUNTHER AVENUE
363 FANNING STREET
984 ATLANTIC AVENUE
1370 5 AVENUE
133 WEST  145 STREET
WASHINGTON STREET
112-02 168 STREET
2 WASHINGTON STREET
1729 HARMAN STREET
520 EAST 21 STREET
100 WYCKOFF STREET
38 WASHINGTON STREET
1279 EAST 17 STREET
243 MONTAUK AVENUE
135 EAST 55 STREET
42 NICHOLS AVENUE
937 71 STREET
52-09 90 STREET
7723 20 AVENUE
21 WEST STREET
35-27 80 STREET
1321 DAHILL ROAD
41-43 77 STREET
310 PATCHEN AVENUE
109 GRATTAN STREET
50 EAST 19 STREET
90-27 53 AVENUE
154-14 132 AVENUE
87-19 52 AVENUE
1916 PACIFIC STREET
147-22 106 AVENUE
7801 20 AVENUE
1655 FLATBUSH AVENUE
152 AVENUE C
342 EAST 241 STREET
4612 THIRD AVENUE
175-20 LINDEN BOULEVARD
707 EAST 96 STREET
40 STREET
1104 EAST TREMONT AVENUE
BOSTON ROAD
180 NORTH 7 STREET
521 WEST 42 STREET
671 WESTCHESTER AVENUE
191 HENRY STREET
501 EAST 185 STREET
79-25 WINCHESTER BOULEVARD
1996 ANTHONY AVENUE
1035 BOYNTON AVENUE
455 EAST 148 STREET
60-15 54 AVENUE
88 SAINT EDWARDS STREET
572 WARREN STREET
1120 WILLIAMS COURT
QUEENS BOULEVARD
17 EAST 124 STREET
35-63 95 STREET
984 METROPOLITAN AVENUE
105 STREET
131 GREENPOINT AVENUE
130 HICKS STREET
102 BAYARD STREET
BROOKVILLE BOULEVARD
315 EDGAR ALLAN POE STREET
2558 GRAND CONCOURSE
21-85 34 AVENUE
125-06 111 AVENUE
3915 LACONIA AVENUE
1532 39 STREET
73 MONROE STREET
519 WEST   47 STREET
6 AVENUE
822 OCEAN AVENUE
MARCY AVENUE
1941 76 STREET
19 AVENUE
1674 PARK AVENUE
83 COFFEY STREET
29-10 159 STREET
5 LINCOLN AVENUE
330 LAFAYETTE STREET
1578 LEXINGTON AVENUE
555 WEST 158 STREET
1544 OCEAN PARKWAY
665 WOODWARD AVENUE
3840 GREYSTONE AVENUE
229 WEST KINGSBRIDGE ROAD
35 MARINE AVENUE
5 FLEET WALK
20 RICHMAN PLAZA
246 TROUTMAN STREET
190 ORCHARD STREET
94 GLEN STREET
715 OCEAN PARKWAY
40 VANDERBILT AVENUE
360 EAST 72 STREET
571 WEST 161 STREET
2082 FREDERICK DOUGLASS BOULEVARD
306 TOMPKINS AVENUE
532 ST MARKS AVENUE
519 WEST 47 STREET
24-35 STEINWAY STREET
725 OCEAN PARKWAY
4602 3 AVENUE
345 ELDERT STREET
41-01 71 STREET
2401 DAVIDSON AVENUE
1218 GLENWOOD ROAD
453 COLUMBIA STREET
206 PARKVILLE AVENUE
660 FAIRVIEW AVENUE
580 CROTONA PARK SOUTH
320 STERLING STREET
868 AMSTERDAM AVENUE
716 ARGYLE ROAD
2353 PACIFIC STREET
507 CONCORD AVENUE
272 PARKVILLE AVENUE
160 MADISON AVENUE
690 SENECA AVENUE
88-06 PARSONS BOULEVARD
232 PARKVILLE AVENUE
4035 ATLANTIC AVENUE
1711 HOE AVENUE
51-40 66 STREET
72-10 41 AVENUE
104-22 88 AVENUE
55 CLARK STREET
58-10 ST FELIX AVENUE
300 PARKVILLE AVENUE
7314 12 AVENUE
438 CHAUNCEY STREET
657 FAIRVIEW AVENUE
918 7 AVENUE
1505 PARK AVENUE
720 EAST 8 STREET
1691 EAST 174 STREET
770 GATES AVENUE
43 COLUMBIA PLACE
69-01 35 AVENUE
BELL BOULEVARD
214 WEST 92 STREET
7721 5 AVENUE
1128 MYRTLE AVENUE
31 DIVISION AVENUE
ROOSEVELT AVENUE
719 EAST 8 STREET
2396 MORRIS AVENUE
172 EAST 89 STREET
676 SENECA AVENUE
52-02 92 STREET
3943 LACONIA AVENUE
27 EAST   29 STREET
58 STREET
220-06 67 AVENUE
554 TRAVIS AVENUE
753 EAST 5 STREET
119 MAC DOUGAL STREET
106 EAST 15 STREET
102-22 PARK LANE SOUTH
52-19 92 STREET
624 ACADEMY STREET
718 FRANKLIN AVENUE
10 AVENUE
BRICKTOWN WAY
170 WEST 107 STREET
38-11 30 AVENUE
97-23 127 STREET
781 CLARKSON AVENUE
897 EMPIRE BOULEVARD
76-26 BROADWAY
2107 1 AVENUE
1601 AVENUE V
275 HULL STREET
2037 82 STREET
163 LUDLOW STREET
103-02 29 AVENUE
CHERRY CLINTON PLAYGROUND
548 EAST 4 STREET
89-25 PARSONS BOULEVARD
139-38 246 STREET
1701 SAINT PETERS AVENUE
1503 WALTON AVENUE
22-55 38 STREET
21-64 UTOPIA PARKWAY
AUSTIN STREET
4924 AVENUE H
BROOME STREET
40-08 NATIONAL STREET
961 REV JAMES A POLITE AVENUE
BROADWAY
60-60 84 STREET
860 ST JOHNS PLACE
831 SWINTON AVENUE
1936 84 STREET
401 WEST  165 STREET
581 BROADWAY
75-26 60 LANE
657 ONDERDONK AVENUE
426 EASTERN PARKWAY
1764 WALTON AVENUE
90 PINE STREET
82-20 ASTORIA BOULEVARD
2299 ADAM C POWELL BOULEVARD
TROY AVENUE
WEST  142 STREET
2367 60 STREET
332 EAST 29 STREET
8101 NARROWS AVENUE
1 WEST 121 STREET
560 WEST 126 STREET
1029 BRYANT AVENUE
17 MACDOUGAL STREET
155-40 78 STREET
114 HENWOOD PLACE
224 HEGEMAN AVENUE
1124 CLARKSON AVENUE
786 SARATOGA AVENUE
1293 EAST 46 STREET
31-29 VERNON BOULEVARD
1850 BILLINGSLEY TERRACE
2566 HONE AVENUE
73 AVENUE
70-21 31 AVENUE
753 EAST 147 STREET
1751 UNDERCLIFF AVENUE
COFFEY SQUARE
245 60 STREET
105 WILLIS AVENUE
138-49 102 AVENUE
522 PUTNAM AVENUE
WEST 251 STREET
35-28 80 STREET
50-24 96 STREET
656 EAST  176 STREET
201 WEST 136 STREET
2474 EAST 24 STREET
362 WEST 127 STREET
400 WEST 55 STREET
1930 GROVE STREET
132-06 154 STREET
32 EAST KINGSBRIDGE ROAD
160 VERMILYEA AVENUE
326 EAST 29 STREET
429 QUENTIN ROAD
496 GRAND STREET
9 BUSHWICK AVENUE
1591 BRUCKNER BOULEVARD
104-65 122 STREET
441 WEST 48 STREET
1703 ST PETERS AVENUE
1735 TOWNSEND AVENUE
2505 BARKER AVENUE
353 WEST 127 STREET
3 WEST 121 STREET
76-22 86 AVENUE
485 TROY AVENUE
1701 ST PETERS AVENUE
1 ST NICHOLAS TERRACE
2811 LAWTON AVENUE
97-02 23 AVENUE
525 TROY AVENUE
64-24 228 STREET
364 WEST 127 STREET
575 EXTERIOR STREET
173 LAMPED LOOP
158 LINDEN BOULEVARD
710 HUNTS POINT AVENUE
114-59 LEFFERTS BOULEVARD
90 LAUREL HILL TERRACE
927 VICTORY BOULEVARD
535 TROY AVENUE
59-19 67 AVENUE
34 STEPHENS COURT
620 EAST 137 STREET
520 EAST 137 STREET
650 ACADEMY STREET
62 EAST   66 STREET
1296 PACIFIC STREET
191 ARLINGTON AVENUE
482 FT WASHINGTON AVENUE
1805 73 STREET
113 RIVINGTON STREET
424 AMSTERDAM AVENUE
109-02 46 AVENUE
1060 RHINELANDER AVENUE
219 MONROE STREET
946 BRONX PARK SOUTH
67 AVENUE
WEST  106 STREET
EAST   19 STREET
570 WEST 193 STREET
724 CLAWSON STREET
486 COLUMBIA STREET
CLIFTON PLACE
1807 73 STREET
104 KELL AVENUE
1685 CASTLE HILL AVENUE
84-10 34 AVENUE
67-54 80 STREET
1311 48 STREET
BEDFORD PARK BOULEVARD
1423 AMSTERDAM AVENUE
660 WILLOUGHBY AVENUE
660 GATES AVENUE
1991 BRONXDALE AVENUE
3111 CHURCH AVENUE
252 12 STREET
504 SCHROEDERS AVENUE
31 STREET
149-07 HOOKCREEK BOULEVARD
279 QUENTIN ROAD
2626 BATH AVENUE
143-50 HOOVER AVENUE
736 BERGEN STREET
28 FLEET WALK
155-42 79 STREET
510 EAST 185 STREET
3112 AVENUE I
98 LAWRENCE AVENUE
45-58 VERNON BOULEVARD
1006 SENECA AVENUE
1242 46 STREET
812 EAST 168 STREET
30-47 92 STREET
204 WEST 101 STREET
424 BRONX PARK AVENUE
32-44 44 STREET
AVENUE C
283 WEST 115 STREET
60-27 54 AVENUE
110 6 AVENUE
58 EAST  132 STREET
1174 WEST FARMS ROAD
53 CLAY STREET
CROSS ISLAND PARKWAY
730 BERGEN STREET
347 UNION AVENUE
EAST KINGSBRIDGE ROAD
324 NORTH BURGHER AVENUE
8 SOUTH 4 STREET
1805 EAST 17 STREET
37-11 PRINCE STREET
2724 UNIVERSITY AVENUE
3330 PEARSALL AVENUE
PARK AVENUE
67 WEST 91 STREET
1819 GEORGE STREET
464 WEST  150 STREET
104-17 116 STREET
117 WEST 70 STREET
1344 THERIOT AVENUE
339 EAST 108 STREET
187-35 HILLSIDE AVENUE
504 WEST 168 STREET
802 EAST 227 STREET
606 WEST   30 STREET
4646 PARK AVENUE
735 GATES AVENUE
309 WEST 43 STREET
1368 PARK PLACE
204 BEACH 44 STREET
34 NORTH 7 STREET
992 AMSTERDAM AVENUE
648 SCHROEDERS AVENUE
2060 PITKIN AVENUE
4385 VIREO AVENUE
4100 THROGS NECK EXPRESSWAY
WEST 48 STREET
31-34 80 STREET
91-14 175 STREET
7501 RIDGE BOULEVARD
662 WASHINGTON AVENUE
415 WEST 52 STREET
1249 CLAY AVENUE
75-06 JAMAICA AVENUE
303 MILFORD STREET
243 EAST 27 STREET
85 AVENUE
2265 OLINVILLE AVENUE
17 WEST  125 STREET
1902 NEPTUNE AVENUE
30-88 36 STREET
153 CENTRAL AVENUE
59-11 74 STREET
1525 UNIONPORT ROAD
34-46 91 STREET
SEXTON PLACE
1815 GRAND CONCOURSE
EAST 216 STREET
180 SOUTH 9 STREET
139 78 STREET
183 BEACH 101 STREET
160 WEST 25 STREET
15 MENAHAN STREET
886 5 AVENUE
VAN CORTLANDT AVENUE EAST
2154 61 STREET
1047 OLMSTEAD AVENUE
40 AVENUE
61-88 DRY HARBOR ROAD
12 BRIGHTON 10 COURT
589 CENTRAL AVENUE
2016 EAST 23 STREET
131 FORT GEORGE AVENUE
38 RED CEDAR LANE
84-02 159 STREET
668 HOWARD AVENUE
350 BEACH 80 STREET
445 49 STREET
60-65 55 STREET
2040 MCGRAW AVENUE
114 AUTUMN AVENUE
2411 EAST 3 STREET
549 82 STREET
1344 THIERIOT AVENUE
50-25 34 STREET
126 WEST 55 STREET
SURF AVENUE
METROPOLITAN AVENUE
1625 11 AVENUE
755 FENIMORE STREET
54 STREET
285 MCKIBBEN STREET
11 BOONE STREET
EXTERIOR STREET
600 WEST 161 STREET
63 PUTNAM AVENUE
2726 BROADWAY
1114 GERARD AVENUE
WEST   73 STREET
2337 85 STREET
2376 60 STREET
24 EAST 39 STREET
437 WEST 36 STREET
885 TROY AVENUE
61 HAMILTON PLACE
3920 BRONX BOULEVARD
79 EAST 7 STREET
20 WEST 112 STREET
100 FT WASHINGTON AVENUE
2925 WEST 16 STREET
20-02 48 STREET
41 ST NICHOLAS TERRACE
41-09 21 AVENUE
104-41 92 AVENUE
1155 EAST 35 STREET
6118 5 AVENUE
69 AUTUMN AVENUE
43 CLINTON STREET
20 WEST 111 STREET
2833 BRIGHTON 3 STREET
STATE ROAD
1501 UNDERCLIFF AVENUE
110 SENECA STREET
536 WEST   50 STREET
1358 CLAY AVENUE
2501 86 STREET
420 LENOX AVENUE
JOHN F KENNEDY AIRPORT
453 OLD MILL ROAD
39 STREET
18-41 123 STREET
90 SAINT MARKS PLACE
277 WEST 127 STREET
203 WEST 103 STREET
141 WYONA STREET
4501 MATILDA AVENUE
EAST 93 STREET
119-07 SPRINGFIELD BOULEVARD
100 MAIDEN LANE
78 RIVERSIDE DRIVE
GRAND AVENUE
EAST   12 STREET
1933 84 STREET
65 PUTNAM AVENUE
180 OCEAN PARKWAY
514 WEST 136 STREET
490 BROADWAY
2364 TIEBOUT AVENUE
95 TEN EYCK STREET
209 EAST 66 STREET
300 PUTNAM AVENUE
975 WASHINGTON AVENUE
OCEAN AVENUE
204 WEST 109 STREET
DEGRAW STREET
4459 MATILDA AVENUE
119 MACDOUGAL STREET
47 TALARICO COURT
571 ISHAM STREET
339 EAST 239 STREET
670 WEST 193 STREET
319 WEST 145 STREET
665 THWAITES PLACE
480 KISSEL AVENUE
118-24 FRANCIS LEWIS BOULEVARD
24-00 90 PLACE
1244 PACIFIC STREET
105-27 170 STREET
BERGEN STREET
767 3 AVENUE
208 HARRISON AVENUE
97-61 CORONA AVENUE
362 90 STREET
120-02 SMITH STREET
1605 VILLAGE LANE
WHITE PLAINS ROAD
247 STREET
537 82 STREET
202 YORK STREET
116-02 FRANCIS LEWIS BOULEVARD
1030 PRESIDENT STREET
584 EAST 23 STREET
EASTERN PARKWAY
2260 BRONX PARK EAST
340 CANAL STREET
114 WEST 109 STREET
600 WEST 246 STREET
90-01 SHORE FRONT PARKWAY
205 WEST 109 STREET
205 WEST 119 STREET
EAST   40 STREET
65 SAINT NICHOLAS AVENUE
115-12 FRANCIS LEWIS BOULEVARD
313 CANAL STREET
59-01 74 STREET
WEST   34 STREET
112 BAY 37 STREET
2971 SHELL ROAD
140 NASSAU STREET
226-07 HORACE HARDING EXPRESSWAY
326 CANAL STREET
401 WEST 129 STREET
201 PEARL STREET
34-15 89 STREET
127 8 AVENUE
430 EASTERN PARKWAY
154-05 UNION TURNPIKE
775 COLUMBUS AVENUE
36 AVENUE
2573 PITKIN AVENUE
45 HOWARD STREET
118 WEST 3 STREET
128-02 7 AVENUE
157 WEST 143 STREET
131 BELMONT AVENUE
170 SCHAEFER STREET
395 MONROE STREET
97-63 CORONA AVENUE
230 WEST  105 STREET
623 JEROME STREET
908 EAST  181 STREET
472 WILLIS AVENUE
65 ARDEN STREET
86-15 208 STREET
8022 5 AVENUE
18 MT MORRIS PARK WEST
259 FRONT STREET
174 STREET
GREENPOINT AVENUE
1460 52 STREET
RICHMOND ROAD
106-45 64 ROAD
15-68 150 STREET
340 WEST 42 STREET
33-16 14 STREET
896 EAST NEW YORK AVENUE
557 EAST 52 STREET
35 BEDFORD STREET
149-05 121 STREET
3956 CARPENTER AVENUE
226 7 AVENUE
35 HILLSIDE AVENUE
1215 LINCOLN PLACE
1719 STERLING PLACE
WEST  179 STREET
277 EASTERN PARKWAY
2094 5 AVENUE
731 EAST  221 STREET
30-98 STEINWAY STREET
26 AVENUE
2645 BRIGGS AVENUE
157 WEST  228 STREET
2712 EAST 19 STREET
147-41 FERNDALE AVENUE
SAWYER AVENUE
66-07 MAURICE AVENUE
2025 VALENTINE AVENUE
1667 GRAND AVENUE
EAST 35 STREET
911 MELROSE AVENUE
71-59 169 STREET
54 WEST 174 STREET
1131 MANOR AVENUE
114 EBONY COURT
79-34 PARSONS BOULEVARD
70 LAUREL HILL TERRACE
ATLANTIC AVENUE
75 BARUCH DRIVE
1718 GRAND AVENUE
426 EAST  162 STREET
343 GOLD STREET
2128 8 AVENUE
85 AMERSFORT PLACE
59 STREET
724 53 STREET
WESTCHESTER AVENUE
5805 5 AVENUE
1488 EAST 53 STREET
609 WEST  177 STREET
74-11 CALDWELL AVENUE
309 5 AVENUE
22-41 WHITESTONE EXPRESSWAY
1350 WASHINGTON AVENUE
SPEEDWELL AVENUE
218 BAY 20 STREET
252-12 72 AVENUE
33 CATON PLACE
307 WEST 38 STREET
139-16 GLASSBORO AVENUE
GENESEE AVENUE
88-63 76 STREET
8661 16 AVENUE
EAST  108 STREET
BRADLEY AVENUE
51 MONROE STREET
147-15 183 STREET
33 BOND STREET
1872 FULTON STREET
GRAND CONCOURSE
185 PARK HILL AVENUE
315 EAST 40 STREET
132-20 107 STREET
166 STREET
1398 GRAND CONCOURSE
25-63 MCINTOSH STREET
PLAZA 67
332 56 STREET
15 AVENUE
514 WEST 28 STREET
69 STREET
415 MYRTLE AVENUE
104-19 48 AVENUE
2077 PACIFIC STREET
91-03 48 AVENUE
852 41 STREET
98-09 ROOSEVELT AVENUE
340 WEBSTER AVENUE
53-11 197 STREET
71 STREET
405 WILLIAMS AVENUE
7220 17 AVENUE
227 23 STREET
MATTHEWS AVENUE
1129 ST LAWRENCE AVENUE
3640 BRONX BOULEVARD
2183 BOGART AVENUE
139-18 GLASSBORO AVENUE
352 STERLING STREET
747 THOMAS BOYLAND STREET
179 MONROE STREET
1645 GRAND AVENUE
WEST 110 STREET
703 FENIMORE STREET
CATON AVENUE
59-18 69 PLACE
109-50 113 STREET
1701 AVENUE X
NORTHFIELD AVENUE
140 WEST 111 STREET

Can location_type , incident zip , incident_address be empty?

1. location type is described as "Describes the type of location used in the address information" , Its dependent on incident address so it can be empty
2. incident zip is also dependent on incident address therefore it can be empty in cases such as the address provided isn't complete ,miss spelled or doesn't exist
3. incident_address can be empty if other incident addresses are provided. like landmark , facility_type , taxi , bridge . 
I'll look into these at last lets look at independent columns first , those are easier to clean / judge

In [37]:
na_incident_zip = df['incident_zip'].isna()
with pd.option_context('display.max_rows',None,
                       'display.max_columns',None):
    display(df.loc[na_incident_zip].head())

canTellZip = ['location_type','incident_zip','incident_address','street_name',
              'cross_street1','cross_street2','intersection_street_1','intersection_street_2',
              'address_type','city','landmark','facility_type','community_board','council_district',
              'police_precinct','bbl','borough','x_coordinate_state_plane','y_coordinate_state_plane',
              'park_facility_name','park_borough','vehicle_type','taxi_company_borough',
              'taxi_pick_up_location']

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T02:39:38.000,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,68504665,2026-03-31T01:58:12.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,RISSE STREET,RISSE STREET,PAUL AVENUE,SEDGWICK AVENUE,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T01:58:12.000,Unspecified BRONX,NaN,Unspecified,NaN,BRONX,NaN,NaN,UNKNOWN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,68508243,2026-03-30T23:51:04.000,2026-03-31T00:40:05.000,NYPD,New York City Police Department,Encampment,NaN,NaN,Subway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Closed,NaN,The New York City Police Department responded ...,2026-03-31T00:40:10.000,Unspecified MANHATTAN,NaN,Unspecified,NaN,MANHATTAN,987638.0,201032.0,MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,F,F Uptown & Queens,NaN,Platform,40.718462,-73.987778,POINT (-73.987777955856 40.718462481372)
721,68510470,2026-03-30T23:04:00.000,NaN,DOT,Department of Transportation,Street Light Condition,Lamppost Knocked Down,Location Type: Intersection,NaN,NaN,NaN,NaN,NaN,NaN,ROCKAWAY BLVD,VAN WYCK EXPY,INTERSECTION,NaN,NaN,NaN,Open,NaN,NaN,NaN,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,68509450,2026-03-30T22:38:07.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,31 STREET,31 STREET,ASTORIA BOULEVARD,ASTORIA BOULEVARD,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-30T22:38:07.000,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
with pd.option_context('display.max_rows',None,
                       'display.max_columns',None):
    display(df.head())

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,council_district,police_precinct,bbl,borough,x_coordinate_state_plane,y_coordinate_state_plane,open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location
0,68509446,2026-03-31T02:39:38.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,NaN,65 ROAD,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T02:39:38.000,Unspecified QUEENS,NaN,Unspecified,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68506247,2026-03-31T02:30:56.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10031.0,CONVENT AVENUE,CONVENT AVENUE,WEST 133 STREET,WEST 135 STREET,NaN,NaN,BLOCKFACE,MANHATTAN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T02:30:56.000,09 MANHATTAN,NaN,Precinct 26,NaN,MANHATTAN,NaN,NaN,UNKNOWN,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68503135,2026-03-31T02:26:57.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11223.0,NaN,NaN,NaN,NaN,AVENUE S,WEST 7 STREET,INTERSECTION,BROOKLYN,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T02:26:57.000,11 BROOKLYN,43.0,Precinct 62,NaN,BROOKLYN,989974.0,158253.0,UNKNOWN,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.601042,-73.979387,POINT (-73.979387264647 40.601042365906)
3,68501976,2026-03-31T02:26:00.000,2026-03-31T02:59:00.000,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,42-71 79 STREET,79 STREET,WOODSIDE AVENUE,45 AVENUE,NaN,NaN,ADDRESS,ELMHURST,NaN,NaN,Closed,NaN,DSNY already has a request to investigate this...,2026-03-31T12:00:00.000,04 QUEENS,25.0,Precinct 110,4.015250e+09,QUEENS,1015808.0,210118.0,PHONE,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.743346,-73.886114,POINT (-73.886113509027 40.74334566695)
4,68509447,2026-03-31T02:17:11.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11101.0,43 STREET,43 STREET,35 AVENUE,NORTHERN BOULEVARD,NaN,NaN,BLOCKFACE,QUEENS,NaN,NaN,Open,NaN,The Department of Transportation referred this...,2026-03-31T02:17:11.000,01 QUEENS,NaN,Precinct 114,NaN,QUEENS,NaN,NaN,UNKNOWN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
subset2

,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status
0,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Open
1,CONVENT AVENUE,WEST 133 STREET,WEST 135 STREET,NaN,NaN,BLOCKFACE,MANHATTAN,NaN,NaN,Open
2,NaN,NaN,NaN,AVENUE S,WEST 7 STREET,INTERSECTION,BROOKLYN,NaN,NaN,Open
3,79 STREET,WOODSIDE AVENUE,45 AVENUE,NaN,NaN,ADDRESS,ELMHURST,NaN,NaN,Closed
4,43 STREET,35 AVENUE,NORTHERN BOULEVARD,NaN,NaN,BLOCKFACE,QUEENS,NaN,NaN,Open

1. Incident address may be empty because its defined as "House number of incident address provided by submitter" , What if the incident didn't happen in a house, I can't mannually check if each of its value is a correct address or not
2. Street name could be empty cause its defined as  "Street name of incident address provided by the submitter" , can't check if a street name is a valid address or not
3. cross_street and intersection_street are dependent 
4. address type is defined as "Type of incident location information available." So if no address provided then it could be nan .
5. city shouldn't have nan values , Maybe when a location is along the border of the city then it can be nan ?  We can populate this using other columns
6. Landmark can definetely be empty cause not every incident location identitfies as a landmark
7. Not every incident location identifies as a facility 
8. status , we have already dealt with this once

In [40]:
# Start coding from here onwards next time 
td = df.copy()

In [41]:
df.isnull().sum()

unique_key                             0
created_date                           0
closed_date                        41043
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          2820
descriptor_2                      125067
location_type                      37166
incident_zip                        2642
incident_address                   12277
street_name                        12281
cross_street_1                     63730
cross_street_2                     63705
intersection_street_1              72611
intersection_street_2              72529
address_type                        1705
city                               10626
landmark                           91597
facility_type                     199346
status                                 0
due_date                          199254
resolution_description             13782
resolution_action_updated_date     12180
community_board                        0
council_district                   11684
police_precinct                        0
bbl                                33808
borough                                0
x_coordinate_state_plane           10593
y_coordinate_state_plane           10575
open_data_channel_type                 0
park_facility_name                   112
park_borough                           0
vehicle_type                      190470
taxi_company_borough              199848
taxi_pick_up_location             197960
bridge_highway_name               198357
bridge_highway_direction          198785
road_ramp                         198826
bridge_highway_segment            198360
latitude                           10602
longitude                          10602
location                           10602
dtype: int64

In [42]:
td = td.drop(['unique_key','created_date','closed_date','agency','agency_name','complaint_type','descriptor','descriptor_2','location_type',
         'status','due_date','resolution_description','resolution_action_updated_date','community_board','council_district','police_precinct',
         'bbl','borough','x_coordinate_state_plane','y_coordinate_state_plane','open_data_channel_type','latitude','longitude','location'],axis=1)

In [43]:
td.loc[na_incident_zip]

,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
0,NaN,65 ROAD,65 ROAD,POWER ROAD,102 STREET,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,RISSE STREET,RISSE STREET,PAUL AVENUE,SEDGWICK AVENUE,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,MANHATTAN,NaN,NaN,NaN,F,F Uptown & Queens,NaN,Platform
721,NaN,NaN,NaN,NaN,NaN,ROCKAWAY BLVD,VAN WYCK EXPY,INTERSECTION,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,NaN,31 STREET,31 STREET,ASTORIA BOULEVARD,ASTORIA BOULEVARD,NaN,NaN,BLOCKFACE,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,Cross Island Pkwy,North/Bronx Bound,Ramp,Bell Blvd (Exit 32)
199969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,Cross Island Pkwy,North/Bronx Bound,Roadway,Bell Blvd (Exit 32) - Throgs Neck Br Bronx New...
199973,NaN,NaN,NaN,NaN,NaN,98 STREET,98 STREET,INTERSECTION,NaN,NaN,DSNY Garage,Unspecified,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,BQE/Gowanus Expwy,East/Bronx Bound,Roadway,Roosevelt Ave / Broadway (Exit 37) - Broadway ...
199993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unspecified,QUEENS,NaN,NaN,NaN,Queensboro/59th St Br,Queens Bound,Roadway,Lower Level

For every column ask ,
1. Can this column have nan values? If yes then when?
2. Check if that column has nan only when its supposed to have nan.

Data cleaning workflow
1. Check nan , are the nan's valid?? What is the status of all the nan's , intentional or accident/error ? har ek column ko izzat se time do
2. Will check if we can fill in the other values using other column values
3. We should have a clear idea of all the columns , how they work , when is what filled , when is it not supposed to be filled

In [44]:
df.created_date

0         2026-03-31T02:39:38.000
1         2026-03-31T02:30:56.000
2         2026-03-31T02:26:57.000
3         2026-03-31T02:26:00.000
4         2026-03-31T02:17:11.000
                   ...
199995    2026-03-12T12:42:00.000
199996    2026-03-12T12:41:52.000
199997    2026-03-12T12:41:50.000
199998    2026-03-12T12:41:46.000
199999    2026-03-12T12:41:39.000
Name: created_date, Length: 200000, dtype: str

In [45]:
df.created_date = pd.to_datetime(df.created_date,format="%Y-%m-%dT%H:%M:%S.%f")
df.closed_date = pd.to_datetime(df.closed_date,format="%Y-%m-%dT%H:%M:%S.%f")

df["created_date_only"] = df.created_date.dt.date
df["closed_date_only"] = df.closed_date.dt.date

df["created_time_only"] = df.created_date.dt.time
df["closed_time_only"] = df.closed_date.dt.time

df['response_time'] = df['closed_date'] - df['created_date']
df['response_time']

0                    NaT
1                    NaT
2                    NaT
3        0 days 00:33:00
4                    NaT
               ...
199995   0 days 03:13:00
199996   0 days 00:48:40
199997               NaT
199998   1 days 01:03:04
199999   0 days 20:14:57
Name: response_time, Length: 200000, dtype: timedelta64[us]

In [46]:
df['response_time'] = df['response_time'].dt.total_seconds().apply(lambda x : x / 3600)

In [47]:
df.response_time.agg(['min','max'])

min   -336.000000
max    438.881944
Name: response_time, dtype: float64

In [48]:
df.loc[df['created_date'] > df['closed_date'],['created_date','closed_date']]
# Gotta remove these columns

df = df.drop(df[df['created_date'] > df['closed_date']].index,axis=0)

In [49]:
df.loc[df.response_time < 0.33,['created_date','closed_date','status']]
# Well we don't need these either, these won't help us predict response time
# Setting the minimum response time to 20 minutes because thats a minimum minutes range I expect for some complaints to be realistically resolved

              created_date         closed_date  status
5      2026-03-31 02:14:08 2026-03-31 02:14:08  Closed
7      2026-03-31 02:05:26 2026-03-31 02:05:26  Closed
8      2026-03-31 02:03:02 2026-03-31 02:03:02  Closed
12     2026-03-31 02:01:14 2026-03-31 02:01:14  Closed
26     2026-03-31 01:49:21 2026-03-31 01:49:21  Closed
...                    ...                 ...     ...
199955 2026-03-12 12:45:48 2026-03-12 12:45:48  Closed
199959 2026-03-12 12:45:08 2026-03-12 13:03:56  Closed
199974 2026-03-12 12:43:42 2026-03-12 12:51:43  Closed
199984 2026-03-12 12:42:44 2026-03-12 12:42:44    Open
199985 2026-03-12 12:42:35 2026-03-12 12:59:01  Closed

[21924 rows x 3 columns]

In [50]:
for i in df.complaint_type.unique():
    print(i)

Street Condition
Derelict Vehicles
Illegal Parking
Noise - Street/Sidewalk
Traffic
Noise - Residential
Drug Activity
Noise - Vehicle
Blocked Driveway
Dirty Condition
Homeless Person Assistance
Consumer Complaint
Non-Emergency Police Matter
Noise - Park
Noise - Commercial
Cannabis Retailer
Urinating in Public
LinkNYC
Smoking or Vaping
Lost Property
Indoor Air Quality
Graffiti
Litter Basket Request
Curb Condition
Missed Collection
Encampment
Illegal Dumping
Abandoned Vehicle
Animal-Abuse
Drinking
Rodent
Street Light Condition
Street Sign - Damaged
Food Establishment
Vendor Enforcement
Illegal Tree Damage
Abandoned Bike
Damaged Tree
Panhandling
Illegal Posting
Obstruction
GENERAL
For Hire Vehicle Complaint
Noise
UNSANITARY CONDITION
PLUMBING
SAFETY
HEAT/HOT WATER
Outdoor Dining
Traffic Signal Condition
Dead Animal
Sewer
ELECTRIC
Water System
Noise - Helicopter
Food Poisoning
WATER LEAK
Lead
Illegal Fireworks
FLOORING/STAIRS
Hazardous Materials
Overgrown Tree/Branches
Sidewalk Condition
DOOR/WINDOW
Taxi Complaint
Air Quality
PAINT/PLASTER
Asbestos
Dumpster Complaint
Highway Condition
Residential Disposal Complaint
Root/Sewer/Sidewalk Condition
Maintenance or Facility
OUTSIDE BUILDING
Animal in a Park
ELEVATOR
Sanitation Worker or Vehicle Complaint
Bike/Roller/Skate
Water Conservation
Elevator
Indoor Sewage
New Tree Request
General Construction/Plumbing
Street Sweeping Complaint
Building/Use
Street Sign - Dangling
APPLIANCE
Taxi Report
Bus Stop Shelter Complaint
Plumbing
Electrical
Commercial Disposal Complaint
Special Projects Inspection Team (SPIT)
Uprooted Stump
Street Sign - Missing
Ferry Inquiry
Dead/Dying Tree
Mobile Food Vendor
Day Care
Unsanitary Pigeon Condition
Disorderly Youth
Unsanitary Animal Pvt Property
Broken Parking Meter
Emergency Response Team (ERT)
Boilers
Wood Pile Remaining
Real Time Enforcement
Lot Condition
Litter Basket Complaint
Violation of Park Rules
Bike Rack
Unleashed Dog
Bench
Drinking Water
Noise - House of Worship
Green Taxi Complaint
Construction Lead Dust
BEST/Site Safety
Bridge Condition
Public Toilet
Investigations and Discipline (IAD)
Industrial Waste
Scaffold Safety
Mold
Special Natural Area District (SNAD)
Harboring Bees/Wasps
Water Quality
Recycling Basket Complaint
Institution Disposal Complaint
For Hire Vehicle Report
E-Scooter
Beach/Pool/Sauna Complaint
Safety
Building Drinking Water Tank
Illegal Animal Kept as Pet
Illegal Animal Sold
Unsanitary Animal Facility
Non-Residential Heat
Lifeguard
Pet Sale
Ferry Complaint
Squeegee
Oil or Gas Spill
Tobacco or Non-Tobacco Sale
AHV Inspection Unit
Posting Advertisement
Tattooing
Animal Facility - No Permit
Highway Sign - Missing
Taxi Compliment
Bus Stop Shelter Placement
FHV Licensee Complaint
Cooling Tower
Incorrect Data
Plant
Dept of Investigations
Trapping Pigeon
Highway Sign - Damaged
School Maintenance
Found Property
Municipal Parking Facility
Snow or Ice
Poison Ivy
Highway Sign - Dangling
DEP Highway Condition
Cranes and Derricks

In [51]:
df = df.drop(df[df['response_time'] < 0.33].index,axis=0)

In [52]:
# impute Nat with something so that it means response not taken

# agency, complaint_type , police precinict , address_type 
# lattiude , longitude ( ye mene iss liye pick kiya cause incomplete info can also be the reason why response was slow or not made and these columns use geovalidation , these are empty means that not enough address was provided )

In [53]:
df.agency.unique()

<StringArray>
[  'DOT',  'DSNY',  'NYPD',   'DHS',  'DCWP',   'OOS',   'OTI', 'DOHMH',
   'TLC',   'DPR',   'HPD',   'DEP',   'EDC',   'DOB',   'DOE']
Length: 15, dtype: str

In [54]:
df[['agency','complaint_type','police_precinct','address_type','latitude','longitude']].info()
# great , three of these don't have any null values

<class 'pandas.DataFrame'>
Index: 178062 entries, 0 to 199999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   agency           178062 non-null  str
 1   complaint_type   178062 non-null  str
 2   police_precinct  178062 non-null  str
 3   address_type     176459 non-null  str
 4   latitude         170572 non-null  float64
 5   longitude        170572 non-null  float64
dtypes: float64(2), str(4)
memory usage: 9.5 MB

In [55]:
# Since this is small , We can remove these
df = df.drop(df.loc[df.address_type.isna(),'closed_date'].index,axis=0)

In [56]:
df = df.drop(df[df.latitude.isna()].index,axis=0)

In [57]:
# lets first look at the columns which have no non null values
df.loc[:,~df.columns.isin(['agency','complaint_type','police_precinct','address_type','latitude','longitude','unique_key','created_date','closed_date','agency_name'])].info()

<class 'pandas.DataFrame'>
Index: 170099 entries, 2 to 199999
Data columns (total 39 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   descriptor                      167938 non-null  str
 1   descriptor_2                    71819 non-null   str
 2   location_type                   149730 non-null  str
 3   incident_zip                    170068 non-null  float64
 4   incident_address                162553 non-null  str
 5   street_name                     162550 non-null  str
 6   cross_street_1                  115934 non-null  str
 7   cross_street_2                  115986 non-null  str
 8   intersection_street_1           113147 non-null  str
 9   intersection_street_2           113224 non-null  str
 10  city                            163167 non-null  str
 11  landmark                        98357 non-null   str
 12  facility_type                   616 non-null     str
 13  status                          170099 non-null  str
 14  due_date                        744 non-null     str
 15  resolution_description          157407 non-null  str
 16  resolution_action_updated_date  158320 non-null  str
 17  community_board                 170099 non-null  str
 18  council_district                169588 non-null  float64
 19  bbl                             151007 non-null  float64
 20  borough                         170099 non-null  str
 21  x_coordinate_state_plane        170099 non-null  float64
 22  y_coordinate_state_plane        170099 non-null  float64
 23  open_data_channel_type          170099 non-null  str
 24  park_facility_name              169993 non-null  str
 25  park_borough                    170099 non-null  str
 26  vehicle_type                    8269 non-null    str
 27  taxi_company_borough            143 non-null     str
 28  taxi_pick_up_location           2019 non-null    str
 29  bridge_highway_name             21 non-null      str
 30  bridge_highway_direction        22 non-null      str
 31  road_ramp                       21 non-null      str
 32  bridge_highway_segment          20 non-null      str
 33  location                        170099 non-null  str
 34  created_date_only               170099 non-null  object
 35  closed_date_only                132091 non-null  object
 36  created_time_only               170099 non-null  object
 37  closed_time_only                132091 non-null  object
 38  response_time                   132091 non-null  float64
dtypes: float64(6), object(4), str(29)
memory usage: 51.9+ MB

In [58]:
df.community_board.unique()

<StringArray>
[              '11 BROOKLYN',                 '04 QUEENS',
               '05 BROOKLYN',                 '08 QUEENS',
                 '12 QUEENS',               '13 BROOKLYN',
                  '05 BRONX',                  '01 BRONX',
               '01 BROOKLYN',               '15 BROOKLYN',
                 '01 QUEENS',               '18 BROOKLYN',
              '12 MANHATTAN',               '10 BROOKLYN',
                  '09 BRONX',              '10 MANHATTAN',
               '03 BROOKLYN',                 '05 QUEENS',
          '01 STATEN ISLAND',              '03 MANHATTAN',
                  '06 BRONX',                 '07 QUEENS',
                  '12 BRONX',              '04 MANHATTAN',
                  '03 BRONX',               '02 BROOKLYN',
                  '07 BRONX',               '12 BROOKLYN',
              '11 MANHATTAN',               '04 BROOKLYN',
                  '04 BRONX',                  '08 BRONX',
                 '80 QUEENS',               '08 BROOKLYN',
                 '10 QUEENS',               '09 BROOKLYN',
                 '09 QUEENS',              '02 MANHATTAN',
                  '02 BRONX',              '07 MANHATTAN',
               '17 BROOKLYN',                 '03 QUEENS',
                 '13 QUEENS',                 '11 QUEENS',
          '03 STATEN ISLAND',               '14 BROOKLYN',
                  '11 BRONX',                 '14 QUEENS',
               '07 BROOKLYN',              '05 MANHATTAN',
              '01 MANHATTAN',              '08 MANHATTAN',
                 '06 QUEENS',               '16 BROOKLYN',
              '09 MANHATTAN',              '06 MANHATTAN',
                 '02 QUEENS',                  '10 BRONX',
          '02 STATEN ISLAND',      'Unspecified BROOKLYN',
               '06 BROOKLYN',                 '83 QUEENS',
             '0 Unspecified',               '55 BROOKLYN',
              '64 MANHATTAN',        'Unspecified QUEENS',
     'Unspecified MANHATTAN',                 '82 QUEENS',
                  '26 BRONX',                  '28 BRONX',
         'Unspecified BRONX',                 '81 QUEENS',
               '56 BROOKLYN',          '95 STATEN ISLAND',
 'Unspecified STATEN ISLAND',                 '84 QUEENS',
                  '27 BRONX']
Length: 77, dtype: str

In [59]:
df.loc[df['community_board'].str.contains('Unspecified',case=False, regex=True),'community_board'] = 'Unspecified'

In [60]:
freq = df['community_board'].value_counts()
df['community_board_encoded'] = df['community_board'].map(freq)
# encoded each community_board with its frequency , for cleaning yk what I did

In [61]:
df.borough.unique()
# One hot encoding will handle this

<StringArray>
['BROOKLYN', 'QUEENS', 'BRONX', 'MANHATTAN', 'STATEN ISLAND', 'Unspecified']
Length: 6, dtype: str

In [62]:
#df.x_coordinate_state_plane.isna().sum()
# x and y coordinate_state_plane are both clean

In [63]:
print(df.open_data_channel_type.unique()) 
print(df.park_borough.unique())
# All good encoding can handle these

<StringArray>
['UNKNOWN', 'PHONE', 'MOBILE', 'ONLINE']
Length: 4, dtype: str
<StringArray>
['BROOKLYN', 'QUEENS', 'BRONX', 'MANHATTAN', 'STATEN ISLAND', 'Unspecified']
Length: 6, dtype: str

In [64]:
display(df.resolution_action_updated_date.unique())
# I can make a column like how many days has it been since resolution action update , I think that could help us predict a lot of things

df['resolution_action_updated_date'] = df.resolution_action_updated_date.astype('datetime64[ns]')

<StringArray>
['2026-03-31T02:26:57.000', '2026-03-31T12:00:00.000',
                       nan, '2026-03-31T01:49:43.000',
 '2026-03-31T02:01:42.000', '2026-03-31T01:49:07.000',
 '2026-03-31T01:54:09.000', '2026-03-31T01:25:57.000',
 '2026-03-31T02:01:12.000', '2026-03-31T01:21:26.000',
 ...
 '2026-03-18T13:09:25.000', '2026-03-12T14:17:05.000',
 '2026-03-12T14:36:59.000', '2026-03-12T13:12:58.000',
 '2026-03-12T22:56:31.000', '2026-03-12T13:57:09.000',
 '2026-03-12T13:52:44.000', '2026-03-12T15:55:00.000',
 '2026-03-12T13:30:38.000', '2026-03-13T13:44:55.000']
Length: 96760, dtype: str

In [65]:
df.resolution_action_updated_date

2        2026-03-31 02:26:57
3        2026-03-31 12:00:00
6                        NaT
9                        NaT
10                       NaT
                 ...
199995   2026-03-12 15:55:00
199996   2026-03-12 13:30:38
199997   2026-03-12 00:00:00
199998   2026-03-13 13:44:55
199999   2026-03-13 00:00:00
Name: resolution_action_updated_date, Length: 170099, dtype: datetime64[ns]

In [66]:
df['time_since_last_resolution_action_day'] = df.resolution_action_updated_date.dt.day
df['time_since_last_resolution_action_hour'] = (df.resolution_action_updated_date - df.created_date).dt.total_seconds() // 3600

In [67]:
df.time_since_last_resolution_action_hour.min()
# Wtf is this value

np.float64(-31568.0)

In [68]:
df.loc[:,['created_date','resolution_action_updated_date','time_since_last_resolution_action_hour']].min()
# This is either a glitch or it has something to do with the inner workings 
# But there is no way for us to know what those inner workings are so , we will have to remove these -ve rows

created_date                              2026-03-12 12:41:39
resolution_action_updated_date            2022-08-17 08:58:46
time_since_last_resolution_action_hour               -31568.0
dtype: object

In [69]:
df.loc[df.time_since_last_resolution_action_hour <= 0].shape # That is a lot of columns we can't just drop these
# We will need to impute these with something

(49714, 52)

We need to impute these with a value such that linear regression won't try to learn from them

In [70]:
closed_date_x_status

   closed_date       status  Possible?  description
0     not_null         Open      False  Human error
1     not_null       Closed       True     Possible
2     not_null          NaN       True  Human error
3     not_null     Assigned      False  Human error
4     not_null      Started      False  Human error
5     not_null      Pending      False  Human error
6     not_null  Unspecified       True  Human error
7          NaN         Open       True     Possible
8          NaN          NaN      False  Human error
9          NaN  In Progress       True     Possible
10         NaN     Assigned       True     Possible
11         NaN      Started       True     Possible
12         NaN      Pending       True     Possible
13         NaN  Unspecified      False  Human error

In [71]:
closed_date_x_status.iloc[6,1]

'Unspecified'

In [72]:
df.iloc[(df['closed_date'].notna()) & (df['status']==closed_date_x_status.iloc[1,1])]

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,longitude,location,created_date_only,closed_date_only,created_time_only,closed_time_only,response_time,community_board_encoded,time_since_last_resolution_action_day,time_since_last_resolution_action_hour
3,68501976,2026-03-31 02:26:00,2026-03-31 02:59:00,DSNY,Department of Sanitation,Derelict Vehicles,Derelict Vehicles,NaN,Street,11373.0,...,-73.886114,POINT (-73.886113509027 40.74334566695),2026-03-31,2026-03-31,02:26:00,02:59:00,0.550000,2497,31.0,9.0
35,68501219,2026-03-31 01:41:31,2026-03-31 02:01:44,NYPD,New York City Police Department,Noise - Park,Loud Talking,NaN,Park/Playground,11223.0,...,-73.970650,POINT (-73.970649628629 40.587730936142),2026-03-31,2026-03-31,01:41:31,02:01:44,0.336944,1454,31.0,0.0
66,68501278,2026-03-31 01:28:48,2026-03-31 01:49:02,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,11232.0,...,-73.996418,POINT (-73.99641815822 40.644691824248),2026-03-31,2026-03-31,01:28:48,01:49:02,0.337222,2919,31.0,0.0
69,68504275,2026-03-31 01:25:58,2026-03-31 01:54:14,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,Residential Building/House,10037.0,...,-73.936127,POINT (-73.936127084377 40.811923091319),2026-03-31,2026-03-31,01:25:58,01:54:14,0.471111,2368,31.0,0.0
75,68504007,2026-03-31 01:23:55,2026-03-31 02:01:26,NYPD,New York City Police Department,Noise - Commercial,Loud Talking,NaN,Club/Bar/Restaurant,11216.0,...,-73.941338,POINT (-73.94133816146 40.682793665961),2026-03-31,2026-03-31,01:23:55,02:01:26,0.625278,3241,31.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,68300565,2026-03-12 12:42:09,2026-03-12 13:52:38,NYPD,New York City Police Department,Encampment,NaN,NaN,Street/Sidewalk,10007.0,...,-74.002731,POINT (-74.002730603521 40.712679886843),2026-03-12,2026-03-12,12:42:09,13:52:38,1.174722,1362,12.0,1.0
199995,68303736,2026-03-12 12:42:00,2026-03-12 15:55:00,DEP,Department of Environmental Protection,Water System,Possible Water Main Break (Use Comments) (WA1),WA1,NaN,11203.0,...,-73.926201,POINT (-73.926201498738 40.654085555145),2026-03-12,2026-03-12,12:42:00,15:55:00,3.216667,3210,12.0,3.0
199996,68298047,2026-03-12 12:41:52,2026-03-12 13:30:32,NYPD,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,NaN,Street/Sidewalk,11249.0,...,-73.960261,POINT (-73.960261410034 40.716631006337),2026-03-12,2026-03-12,12:41:52,13:30:32,0.811111,4246,12.0,0.0
199998,68303589,2026-03-12 12:41:46,2026-03-13 13:44:50,DSNY,Department of Sanitation,Dirty Condition,Trash,Not Cleaned by Property Owner,Yard,11228.0,...,-74.010250,POINT (-74.010250409554 40.611852762534),2026-03-12,2026-03-13,12:41:46,13:44:50,25.051111,3496,13.0,25.0
199999,68302923,2026-03-12 12:41:39,2026-03-13 08:56:36,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,NO HEAT,RESIDENTIAL BUILDING,10452.0,...,-73.924705,POINT (-73.92470475388 40.843455723803),2026-03-12,2026-03-13,12:41:39,08:56:36,20.249167,4228,13.0,11.0

In [73]:
L = []
td = closed_date_x_status
for i in range(14):
    if td.iloc[i,3]=='Human error':
        if td.iloc[i,0]=='not_null':
            if td.iloc[i,1]!=np.nan:
                L.append(df.iloc[(df['closed_date'].notna()) & (df['status']==closed_date_x_status.iloc[i,1])].shape[0])
            else:
                L.append(0)
        else:
            if td.iloc[i,1]!=np.nan:
                L.append(df.iloc[(df['closed_date'].isna()) & (df['status']==closed_date_x_status.iloc[1,1])].shape[0])
            else:
                L.append(0)
    else:
        L.append(np.nan)

closed_date_x_status['count'] = L
print('Size of not possible values:',closed_date_x_status['count'].sum())
print("Size of actual possible values :",df.shape[0] - closed_date_x_status['count'].sum())

Size of not possible values: 498.0
Size of actual possible values : 169601.0

In [74]:
closed_date_x_status

   closed_date       status  Possible?  description  count
0     not_null         Open      False  Human error    2.0
1     not_null       Closed       True     Possible    NaN
2     not_null          NaN       True  Human error    0.0
3     not_null     Assigned      False  Human error  496.0
4     not_null      Started      False  Human error    0.0
5     not_null      Pending      False  Human error    0.0
6     not_null  Unspecified       True  Human error    0.0
7          NaN         Open       True     Possible    NaN
8          NaN          NaN      False  Human error    0.0
9          NaN  In Progress       True     Possible    NaN
10         NaN     Assigned       True     Possible    NaN
11         NaN      Started       True     Possible    NaN
12         NaN      Pending       True     Possible    NaN
13         NaN  Unspecified      False  Human error    0.0

In [75]:
df['status'].isin(['Assigned','Open'])

2          True
3         False
6         False
9         False
10        False
          ...
199995    False
199996    False
199997     True
199998    False
199999    False
Name: status, Length: 170099, dtype: bool

In [76]:
df[df['closed_date'].notnull()].index

Index([     3,     35,     66,     69,     75,    101,    104,    105,    109,
          110,
       ...
       199986, 199987, 199988, 199991, 199992, 199994, 199995, 199996, 199998,
       199999],
      dtype='int64', length=132091)

In [77]:
# This is very small , Removing this won't affect our data much
# Had to check/confirm how to do this in a single like 
# Encountered the memory error for the first time , had to consult ai if my logic was correct or not
df = df.drop(df[(df['closed_date'].notnull()) & (df['status'].isin(['Assigned','Open']))].index,axis=0)

In [78]:
df.council_district.unique()

array([43., 25., 37., 24., 27., 47., 14., 17., 33., 44., 22., 46., 21.,
       10., 18.,  9., 41., 28., 34., 30., 49.,  1., 15., 20., 12.,  3.,
       16., 23., 38., 36., 35., 19.,  8., 32., 29.,  2., 48., 11.,  6.,
       39., 40., 50., 13., 31., 42., 45.,  7., 26.,  4., 51., nan,  5.])

In [79]:
df.council_district.isna().sum()
# Small again , we can remove this
df = df.drop(df[df.council_district.isna()].index,axis=0)

In [80]:
df.bbl.agg(['min','max'])

min    0.000000e+00
max    5.270001e+09
Name: bbl, dtype: float64

In [81]:
df.bbl.value_counts()

bbl
2.025110e+09    315
4.142600e+09    275
3.063150e+09    261
2.046990e+09    255
4.068290e+09    227
               ...
3.013310e+09      1
3.068480e+09      1
4.119470e+09      1
1.001590e+09      1
3.046600e+09      1
Name: count, Length: 62017, dtype: int64

In [82]:
df.bbl.isna().sum()
# Can't remove these 
# what do we do? frequency encoding?
# I am thinking of imputing NaN with lets say 0

np.int64(18402)

In [83]:
df.taxi_company_borough.unique()
df.bridge_highway_name.unique()
# probably onehot encoding , or freq encoding or i just Impute with something , Idk what to impute with

<StringArray>
[                      nan,       'Long Island Expwy',
          'Van Wyck Expwy', 'Henry Hudson Pkwy/Rt 9A',
                  'FDR Dr',   'Queensboro/59th St Br',
      'Grand Central Pkwy',               'Belt Pkwy',
      'Major Deegan Expwy',       'BQE/Gowanus Expwy',
         'Harlem River Dr',          'FDR Southbound']
Length: 12, dtype: str

In [84]:
df.due_date.isna().sum()

np.int64(168347)

In [ ]:
df.facility_type.unique()
# Since there are only two values , i think i can encode it with 1 and 0 , represention not null and null value

<StringArray>
[nan, 'DSNY Garage']
Length: 2, dtype: str

In [ ]:
df.landmark.unique()
# I think frequency encoding should do it

<StringArray>
[                   nan,     'ARLINGTON AVENUE',             '87 DRIVE',
           '149 STREET',      'BAY VIEW AVENUE',        'WALTON AVENUE',
      'EAST 152 STREET',          'WEST STREET',             'AVENUE U',
              '25 ROAD',
 ...
          'FRIEL PLACE',          'HAVEN PLAZA', 'ATLANTIC CENTER MALL',
       'LUCILLE AVENUE',          'PAUW STREET',          'ZEBRA PLACE',
         'MOSCO STREET',      'BEACH 64 STREET',          'JULIUS ROAD',
     'ST ANDREWS PLAZA']
Length: 5206, dtype: str

In [ ]:
df.city.unique()
# I have no idea , frequency encoding??
# Target encoding? but that supposed to be done on the train dataset only
# Nan becomes its own category

<StringArray>
[           'BROOKLYN',            'ELMHURST',             'JAMAICA',
               'BRONX',                   nan,             'ASTORIA',
              'CORONA',            'NEW YORK',           'RIDGEWOOD',
       'STATEN ISLAND',            'FLUSHING',       'FRESH MEADOWS',
       'EAST ELMHURST',              'QUEENS',             'BAYSIDE',
          'OZONE PARK',       'RICHMOND HILL',        'HOWARD BEACH',
       'COLLEGE POINT',      'QUEENS VILLAGE',        'FOREST HILLS',
             'MASPETH',    'SOUTH OZONE PARK',     'JACKSON HEIGHTS',
            'WOODSIDE',       'NEW HYDE PARK',     'OAKLAND GARDENS',
           'SUNNYSIDE',           'REGO PARK',         'KEW GARDENS',
           'MANHATTAN',      'MIDDLE VILLAGE',             'ARVERNE',
 'SOUTH RICHMOND HILL',            'ROSEDALE',          'WHITESTONE',
           'WOODHAVEN',    'LONG ISLAND CITY',        'FAR ROCKAWAY',
     'CAMBRIA HEIGHTS',           'BELLEROSE', 'SPRINGFIELD GARDENS',
              'HOLLIS',         'LITTLE NECK',        'SAINT ALBANS',
           'GLEN OAKS',         'FLORAL PARK',        'BREEZY POINT',
   'LAGUARDIA AIRPORT']
Length: 49, dtype: str

In [ ]:
df.taxi_company_borough.unique()

<StringArray>
[nan, 'BROOKLYN', 'QUEENS', 'BRONX', 'MANHATTAN', 'STATEN ISLAND']
Length: 6, dtype: str

In [111]:
df.borough.notna().shape

(169091,)

In [ ]:
df.location_type.value_counts()['Taxi']
# taxi_company_borough or taxi_pickup_location may be empty but location_type = Taxi cannot be false

np.int64(330)

In [124]:
df.taxi_company_borough.notnull().sum()

np.int64(143)

In [129]:
df.vehicle_type.notna().sum()

np.int64(8269)

In [ ]:
print(df.loc[(df['borough'].notnull()) & (df['taxi_company_borough'].notnull())].shape)
print(df.loc[(df['borough'].isnull()) & (df['taxi_company_borough'].notnull())].shape)
print(df.loc[(df['borough'].isnull()) & (df['taxi_company_borough'].isnull())].shape)
print(df.loc[(df['borough'].notnull()) & (df['taxi_company_borough'].isnull())].shape)
# Just checking this cause both are borough , so i was wondering if both are given at a time

(143, 52)
(0, 52)
(0, 52)
(168948, 52)

- We have 330 taxi records and out of which , only 143 taxi borough records . 
- The amount of data is insufficient to predict even location type taxi , much less extract patterns from taxi company borough 
- Facility , landmark and highway | road ramp are in similar condtions
- Therefore, I believe it would be sufficient to have a column with category taxi , highway, landmark , facility , other

In [130]:
df.vehicle_type.unique()

<StringArray>
[                      nan,                     'Car',
                     'SUV',                     'Van',
                   'Truck',                   'Other',
             'Car Service', 'Ambulette / Paratransit',
            'Commuter Van']
Length: 9, dtype: str

In [ ]:
# For vehicle_type we can idk one hot encode it i guess , There are way too many nulls can't remove them
# Target encoding when using Random forest

In [85]:
# community_board , borough , x_coordinate_state_plane ,y_coordinate_state_plane , open_data_channel_type , park_borough done

In [86]:
# resolution_action_updated_date , status ,  council_district , bbl , vechicle_type , taxi_company_borough , bride_highway_name

In [88]:
#  landmark , facility_type , city , due_date

In [89]:
# Now I pick 6 more Columns other than the 6 columns I already picked and think about what to do with their NaN
# Pick 6 columns other than the one you already picked that can help you predict response time

In [91]:
#workflow of how a record is added and when is it confirmed

#### Hide

##### 4. EDA

$$\huge \texttt{Exploratory data analysis}$$

In [92]:
# Columns that I think might affect Response time
claim = [{'refers to the same agency':['agency','agency']},
         'complaint_type',
         'due_date',
         'resolution_description',
         'resolution_action_updated_date',
         'open_data_channel_type',
         {'description of problem':['descriptor','descriptor_2']},
         {'location':   ['location_type','incident_zip','incident_address', 'street_name', 'cross_street_1', 'cross_street_2',
                            'intersection_street_1', 'intersection_street_2','address_type','city', 'landmark', 'facility_type',
                            'community_board', 'council_district','police_precinct', 'bbl', 'borough', 'x_coordinate_state_plane',
                            'y_coordinate_state_plane','latitude', 'longitude', 'location'],
       'park_location': ['park_facility_name', 'park_borough'],
       'taxi_location': ['taxi_company_borough', 'taxi_pick_up_location'],
       'bridge_location': ['bridge_highway_name',
                            'bridge_highway_direction', 'road_ramp', 'bridge_highway_segment']},]

# Columns that I don't think affect the Response time
NotClaim = ['unique_key', 'created_date', 'closed_date','status']

##### 5. Data transformations

$$\huge \texttt{Data pre-processing}$$
$$\normalsize \texttt{In this section , We are gonna prepare our data for model input}$$

In [93]:
# OneHot-Encoding all the categorical columns at once
"""
X_train , X_test , y_train , y_test = train_test_split(...)

X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

# Train and test might have different categories 
#ex Train has : A, B and Test has : A, C , so columns don't match
#This makes sure , both have same columns , missing ones are filled with 0
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)
"""

"\nX_train , X_test , y_train , y_test = train_test_split(...)\n\nX_train = pd.get_dummies(X_train)\nX_test = pd.get_dummies(X_test)\n\n# Train and test might have different categories \n#ex Train has : A, B and Test has : A, C , so columns don't match\n#This makes sure , both have same columns , missing ones are filled with 0\nX_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)\n"

##### 6. Training

$$\huge \texttt{Model Training}$$
$$\normalsize \texttt{Training the model / trying out different things with the model and improving the result of desired metrics}$$

##### 7. evaluation

$$\huge \texttt{Model evaluation / interpretation}$$
$$\normalsize \texttt{We showcase and interpret the result here}$$